import { legalProfile, type LegalDocument } from "./legal";

type Section = { title: string; paragraphs: string[] };
type Document = { intro: string; sections: Section[] };
const section = (title: string, ...paragraphs: string[]): Section => ({ title, paragraphs });

export function legalContent(document: LegalDocument, locale: string): Document {
  const ru = locale === "ru";
  const operator = legalProfile.operator_name;
  const email = legalProfile.contact_email;
  const documents: Record<LegalDocument, Document> = ru ? {
    terms: {
      intro: "Условия аккаунта, сайта и участия в открытой бете VLTone.",
      sections: [
        section("О сервисе", `${operator} предоставляет доступ к сайту vltstudio.ru, аккаунту и открытой бете музыкальной программы VLTone. Эти условия регулируют использование сайта и аккаунта. Условия лицензий компонентов программы и сторонних плагинов действуют отдельно.`, "Соглашение заключается при установке отдельной отметки о его принятии и успешной регистрации. Простое чтение сайта не является согласием на обработку данных для регистрации или на диагностику."),
        section("Аккаунт", "Для регистрации нужны действующая электронная почта, никнейм и пароль. Указывайте свои данные, храните пароль в тайне и сообщайте оператору о подозрении на доступ посторонних. Никнейм не должен нарушать права других лиц.", "Пользователь должен иметь право самостоятельно заключить это соглашение. Если по закону для этого требуется согласие законного представителя, получите его до регистрации. Не вводите данные других людей без законного основания."),
        section("Открытая бета", "Бета предназначена для знакомства с программой и её тестирования. Функции, лимиты и доступные сборки могут меняться. Актуальные загрузки публикуются на странице версий, персональные лимиты — в аккаунте.", "В программе возможны ошибки и перерывы работы. Сохраняйте резервные копии важных проектов. Оператор не обещает непрерывную работу или пригодность каждой бета-сборки для конкретной задачи. Это не исключает ответственность и права пользователя, которые нельзя ограничить законом."),
        section("Музыка и права", "Вы сохраняете права на созданные вами композиции и материалы. Использование VLTone само по себе не передаёт оператору исключительные права на вашу музыку и не даёт права публиковать её.", "Загружайте и используйте только материалы и плагины, для которых у вас есть необходимые права. Передача файлов в облачный проект нужна для выбранной вами функции и не разрешает их произвольное использование вне этой цели."),
        section("Допустимое использование", "Нельзя получать неразрешённый доступ к чужим аккаунтам, обходить защиту и лимиты, распространять вредоносный код или нарушать работу сервиса. При обнаружении злоупотреблений оператор может ограничить соответствующий доступ. Для выяснения причины и восстановления доступа можно написать оператору.", "AI-ответы могут содержать ошибки. Проверяйте результат перед использованием. Запросы к внешним моделям не следует наполнять персональными данными, конфиденциальными материалами или чужим контентом без основания для передачи."),
        section("Данные и завершение использования", "Обработка персональных данных описана в отдельной политике. Согласие на данные аккаунта и необязательное согласие на диагностику принимаются отдельно от этого соглашения. Рекламные рассылки в эти согласия не включены.", `Вы можете прекратить использование сервиса и запросить закрытие аккаунта по адресу ${email}. После проверки обращения оператор прекращает доступ, отзывает сессии и удаляет данные, для которых больше нет законного основания хранения. Перед закрытием аккаунта сохраните нужные облачные проекты.`),
        section("Изменения и обращения", "На странице указана версия документа. Существенные изменения, требующие нового волеизъявления, не применяются как автоматически полученное согласие. Старая отметка не разрешает новые цели обработки данных.", `Применяется законодательство Российской Федерации. Обращения направляются на ${email}. Спор можно передать в компетентный суд по установленным законом правилам; обязательные права потребителей и субъектов персональных данных сохраняются.`),
      ],
    },
    privacy: {
      intro: "Какие данные получает VLTone, зачем они нужны и как ими управлять.",
      sections: [
        section("Кто обрабатывает данные", `Оператор — ${operator}. Контакт по персональным данным: ${email}. Политика относится к посетителям сайта, владельцам аккаунтов и пользователям связанных онлайн-функций VLTone.`, "Основной сервер и база пользователей находятся в России, в Москве, по сведениям оператора. Адрес сервера не является почтовым адресом оператора. До публикации окончательной редакции необходимо подтвердить сведения о резервных копиях, хостинге и иных привлечённых сервисах."),
        section("Аккаунт и безопасность", "Для создания аккаунта и доступа используются email, никнейм, язык, идентификатор пользователя, даты регистрации и входов. Пароль хранится в виде криптографического хеша. Для подключения приложения также используются идентификатор установки, название устройства, ОС, версия приложения и сведения об устройстве, передаваемые при входе.", "Для защиты входа и подтверждения выбора обрабатываются IP-адрес, данные сессии, версия документа и время принятия. Основания — исполнение пользовательского соглашения, отдельное согласие в пределах заявленных целей, а также обязанности и иные основания, предусмотренные статьёй 6 Закона № 152-ФЗ. Данные, не нужные для этих целей, не запрашиваются."),
        section("Обращения, AI и облачные функции", "Для ответа на обращение используются контактные данные, текст сообщения, сведения о версии программы и добровольно приложенные файлы. Не прикладывайте сведения о других людях, секреты или лишние личные документы. Срок хранения обращения — до решения вопроса, затем не более 30 дней, если другой срок не обусловлен законом или обоснованной защитой прав.", "При использовании AI текст запроса и необходимый контекст проекта могут направляться внешнему поставщику модели. Для облачной совместной работы сервер получает выбранные проекты, их метаданные и загруженные файлы; участники получают доступ в пределах выбранной функции. Согласие при регистрации не является согласием на произвольную передачу любых файлов и персональных данных внешним сервисам.", "До выпуска окончательной политики оператор должен уточнить перечень поставщиков, поручения на обработку, страны и основания передачи. Трансграничная передача, если она осуществляется, требует отдельной проверки и выполнения статьи 12 Закона № 152-ФЗ. Указанный контактный адрес использует сервис Outlook; его размещение также подлежит этой проверке."),
        section("Добровольная диагностика", "Диагностика включается отдельным необязательным согласием. Отказ не ограничивает создание аккаунта. Управлять согласием можно в личном кабинете; сервер прекращает принимать новые диагностические отчёты при отказе.", "Диагностика может содержать идентификаторы пользователя, устройства и сессии, ОС, оборудование, версию программы, нагрузку CPU/DSP, память, настройки аудио, ошибки, названия и версии плагинов, структуру и названия дорожек, маршрутизацию, сведения о сбоях и журналы. Это данные, связанные с аккаунтом, а не обещание анонимной статистики.", "Телеметрия не предназначена для передачи аудиофайлов, MIDI-нот, паролей или полных состояний плагинов. Журналы сбоев могут содержать дополнительный технический контекст. Диагностические записи хранятся не дольше 90 дней с получения; после отзыва согласия подлежат удалению в срок до 30 дней, если нет другого законного основания."),
        section("Cookie и локальное хранение", "При первом посещении общедоступных страниц сайт не создаёт cookie автоматически. Пользователь может разрешить функциональные cookie или продолжить без них. Cookie языка vlt-locale создаётся только при явном выборе языка и хранится до года. Без cookie переключение языка действует только для текущей страницы. Cookie сессии vlt_web_session создаётся при входе или регистрации, хранится до 30 дней и нужна для личного кабинета. Отказ от cookie удаляет текущие cookie языка и входа; публичные страницы остаются доступны, а для нового входа потребуется разрешить cookie сессии.", "Выбор «только необходимые» или «без cookie» хранится в localStorage браузера под ключом vlt-cookie-preference-v1, чтобы не показывать сообщение снова. Сервер не сохраняет этот выбор. Его можно изменить по ссылке «Настройки cookie» в подвале сайта. Рекламные пиксели и внешняя аналитика посещений не подключены; для добавления необязательных cookie потребуется отдельное решение и обновление политики."),
        section("Способы, доступ и сроки", "Обработка автоматизированная и, при разборе обращений, смешанная: сбор, запись, систематизация, накопление, хранение, уточнение, извлечение, использование, предоставление уполномоченным получателям для заявленной цели, блокирование, удаление и уничтожение. Общедоступная публикация персональных данных этим документом не разрешается.", "Доступ предоставляется только уполномоченным лицам для их задач; обработка по поручению требует предусмотренных законом условий. Используются защищённые соединения, хеширование паролей, ограничения доступа и проверка сессий. Безопасность включает организационные меры оператора, а не только программный код.", "Данные аккаунта хранятся, пока он используется и требуется исполнение соглашения. После достижения цели или отзыва согласия данные, для которых нет другого основания, уничтожаются в срок до 30 дней. Документально обоснованные обязательные сроки и защита прав могут требовать отдельного ограниченного хранения. Бессрочное хранение всех данных не устанавливается. Удаление должно охватывать связанные записи, файлы и резервные копии по утверждённому порядку."),
        section("Ваши права", `Вы можете запросить сведения об обработке, доступ, уточнение, блокирование или уничтожение данных, отозвать согласие и потребовать прекращения обработки: ${email}. Начните обращение с почты аккаунта; оператор вправе запросить только сведения, необходимые для подтверждения личности и рассмотрения запроса.`, "На запрос о сведениях оператор отвечает в течение 10 рабочих дней; продление не более чем на 5 рабочих дней возможно с мотивированным уведомлением. Требование о прекращении обработки рассматривается в предусмотренные статьёй 21 сроки. Отзыв согласия не отменяет ранее правомерную обработку и не исключает хранение на другом законном основании.", "Действия оператора можно обжаловать в Роскомнадзор или суд. Если без необходимых данных невозможно поддерживать аккаунт, после их удаления соответствующий доступ прекращается. Отзыв диагностики сам по себе аккаунт не закрывает."),
      ],
    },
    consent: {
      intro: "Отдельное согласие для создания и обслуживания аккаунта. Без рекламы и необязательной диагностики.",
      sections: [
        section("Мой выбор", `Я свободно, своей волей и в своём интересе разрешаю оператору ${operator} обрабатывать перечисленные ниже персональные данные для создания и обслуживания моего аккаунта VLTone, доступа к программе, восстановления входа и защиты аккаунта.`, "Согласие предоставляется отдельной непредустановленной отметкой в форме регистрации и отправкой формы. Оно не объединяется с принятием пользовательского соглашения."),
        section("Какие данные и действия", "Перечень: email, никнейм, язык, хеш пароля, идентификатор аккаунта, IP-адрес регистрации, версия согласия и время его принятия; при использовании аккаунта — данные сессий, входов и привязанных установок, название и идентификатор устройства, ОС, версия программы и технические характеристики, переданные при входе.", "Разрешены автоматизированная и смешанная обработка, сбор, запись, систематизация, накопление, хранение, уточнение, извлечение, использование для заявленной цели, блокирование, удаление и уничтожение. К данным допускаются уполномоченные лица оператора в пределах их задач. Публичное распространение, реклама и необязательная диагностика в это согласие не входят."),
        section("Срок и отзыв", `Согласие действует с регистрации до закрытия аккаунта или его отзыва — в зависимости от того, что наступит раньше. Отозвать его можно письмом на ${email} с темой «Отзыв согласия»; укажите почту аккаунта и требование.`, "После прекращения цели или отзыва обработка прекращается и данные удаляются в срок до 30 дней, если у оператора нет другого законного основания. Необходимые для исполнения соглашения данные могут обрабатываться на этом основании; оператор сообщает его при ответе. Если обслуживание без удаляемых данных невозможно, аккаунт закрывается.", "Без предоставления необходимых данных и этого согласия регистрация через данную форму не выполняется; общедоступные страницы остаются доступны. Для диагностики требуется самостоятельный выбор по отдельному документу."),
      ],
    },
    "diagnostics-consent": {
      intro: "Необязательный выбор, который помогает находить ошибки в VLTone. Можно отказаться без потери аккаунта.",
      sections: [
        section("Цель и добровольность", `Я разрешаю оператору ${operator} обрабатывать диагностические сведения о работе VLTone для выявления и исправления ошибок, проверки совместимости и анализа производительности. Согласие предоставляется отдельной отметкой при регистрации или в личном кабинете.`, "Отказ от этой отметки не препятствует регистрации, входу и основным функциям. Регистрационное согласие не заменяет это согласие."),
        section("Состав и обработка", "Идентификаторы аккаунта, установки и сессии, версия программы, ОС и оборудование; CPU/DSP, память, параметры аудио, число дорожек и клипов, состояние воспроизведения; названия дорожек, структура проекта и маршрутизация, названия и версии плагинов; сведения о сбое и технические журналы.", "Сведения связаны с аккаунтом. Аудиозаписи, MIDI-ноты, пароли и состояния плагинов не входят в штатную телеметрию. Не добавляйте личные сведения в названия дорожек и другие диагностируемые поля.", "Разрешены сбор, запись, систематизация, накопление, хранение, извлечение, использование, блокирование, удаление и уничтожение автоматизированным и смешанным способом. Диагностика доступна уполномоченным специалистам оператора для указанных целей; это не разрешение на публикацию, рекламу или передачу произвольным третьим лицам."),
        section("Срок хранения и отзыв", `Согласие действует до отзыва или закрытия аккаунта. Каждая диагностическая запись хранится не более 90 дней с получения. Отзыв доступен в личном кабинете либо письмом на ${email} с темой «Отключить диагностику».`, "После отзыва сервер прекращает принимать новые диагностические отчёты; ранее полученные сведения удаляются не позднее 30 дней, если отсутствует иное законное основание. Согласие не разрешает бессрочное хранение. Отзыв не закрывает аккаунт."),
      ],
    },
  } : {
    terms: { intro: "Your account, the website and the VLTone open beta.", sections: [
      section("The service", `${operator} operates vltstudio.ru and provides a VLTone account and access to the open beta. These terms cover the website and account. Software component and third-party plugin licences apply separately.`, "You accept these terms using the separate unchecked box and successfully submitting registration. Merely browsing does not provide consent to account data processing or diagnostics."),
      section("Your account", "Use your own valid email, a nickname and a secure password. Keep access credentials private and report suspected unauthorised access. You must have legal capacity to enter these terms or obtain any legally required representative's permission."),
      section("The beta and your music", "Features, limits and builds may change. Current installers appear on the releases page; your limits appear in your account. Beta software may contain errors. Keep backups of important projects. Mandatory statutory rights and liability remain unaffected.", "You keep your rights to your music. Using VLTone does not transfer those rights or authorise publication of your work. Only use content and plugins you are entitled to use. Cloud uploads serve the function you choose."),
      section("Responsible use", "Do not access other accounts without permission, bypass security or limits, distribute malware, or disrupt the service. Access may be restricted for misuse; contact the operator to resolve a restriction. Review AI output and avoid submitting personal or confidential information to external models without an appropriate basis."),
      section("Data and ending use", `The separate privacy policy explains processing. Account consent and optional diagnostic consent are distinct from these terms and do not include marketing. Request account closure at ${email}. Save cloud projects first. The operator verifies the request, revokes access and removes data no longer lawfully needed.`),
      section("Changes and disputes", `Material changes requiring a new choice are not treated as automatically accepted. Russian law applies. Contact ${email}; disputes follow the courts and procedures provided by law. Mandatory consumer and data subject rights remain intact. The Russian document is the governing version; this English text is provided for convenience.`),
    ] },
    privacy: { intro: "What VLTone receives, why it is needed and how you can manage it.", sections: [
      section("The operator", `${operator} is the data operator. Contact: ${email}. This policy covers visitors, account holders and users of connected online features.`, "The operator states that the main server and user database are in Moscow, Russia. This is not the operator's postal address. Backup locations, hosting arrangements and service providers must be confirmed before this draft is published as final."),
      section("Account and security", "Account data includes email, nickname, language, user ID, registration and sign-in times, a password hash, IP address, session identifiers and the document revision and time of acceptance. App sign-in also records linked installation and device identifiers, device name, operating system, app version and supplied hardware details.", "Purposes are account creation, access, recovery and security. Legal bases include the user agreement, separate consent for the stated purposes and other applicable grounds under Article 6 of Russian Federal Law No. 152-FZ."),
      section("Support, AI and cloud services", "Support uses contact details, messages, app details and attachments you choose to send. Keep out unrelated personal information and secrets. Requests are kept until resolved, then for no more than 30 days unless law or a justified rights-protection purpose requires otherwise.", "AI requests and necessary project context may be sent to an external model provider. Cloud collaboration receives selected projects, metadata and uploaded assets and shares them with participants as required by the selected function. Registration does not authorise arbitrary transfers of personal information or files.", "Before final publication the operator must document providers, processing arrangements, countries and legal bases, and fulfil Article 12 where cross-border transfers occur. The contact mailbox uses Outlook and must also be assessed."),
      section("Optional diagnostics", "Diagnostics require a separate optional choice. Refusal does not block registration. You can withdraw in your account; the server then stops accepting new reports.", "Diagnostics may include account, device and session IDs, OS and hardware, version, CPU/DSP load, memory, audio settings, errors, plugins, track names, project structure, routing, crash details and logs. They are linked to your account, not described as anonymous. Normal telemetry does not contain audio, MIDI notes, passwords or plugin state blobs; crash logs may contain additional technical context.", "Each diagnostic record is retained for at most 90 days from receipt and removed within 30 days of withdrawal unless another lawful basis applies."),
      section("Cookies and local storage", "Public pages do not set cookies automatically on a first visit. You may allow functional cookies or continue without them. The vlt-locale cookie is set only when you explicitly choose a language and lasts up to one year. Without cookies, a language switch applies only to the current page. The vlt_web_session cookie is set on sign-in or registration, lasts up to 30 days and is needed for the account area. Choosing no cookies removes the current language and sign-in cookies. Public pages remain available; signing in again requires allowing the session cookie.", "Your 'necessary only' or 'no cookies' choice is stored in your browser's localStorage under vlt-cookie-preference-v1 so the notice does not repeat. The server does not store this choice. Change it through 'Cookie settings' in the footer. There are no advertising pixels or external website analytics. Optional cookies would require a separate decision and an updated policy."),
      section("Methods, access and retention", "Processing is automated or mixed when handling requests: collection, recording, organisation, accumulation, storage, correction, retrieval, use, access for authorised recipients, restriction, deletion and destruction. Public disclosure is not authorised. Access is restricted by role and task; processors require lawful arrangements. Transport protection, password hashing and session checks complement the operator's organisational safeguards.", "Account data is kept while the account and agreement require it. After the purpose ends or consent is withdrawn, data without another legal basis is removed within 30 days. Statutory duties or documented protection of rights may require limited separate retention. There is no blanket indefinite retention. Related files and backups must be included in the deletion procedure."),
      section("Your rights", `Request access, processing information, correction, restriction, deletion or withdrawal at ${email}. Start from your account email. Only information necessary to verify and resolve the request should be requested.`, "Information requests are answered within 10 working days, with a reasoned extension of up to 5 working days where permitted. Cessation requests follow Article 21. Withdrawal does not invalidate past lawful processing or remove other lawful grounds. You can complain to Roskomnadzor or a court. Deleting necessary account data ends the corresponding service; withdrawing diagnostics does not close the account."),
    ] },
    consent: { intro: "Separate consent for your account. No marketing or optional diagnostics.", sections: [
      section("My choice", `I freely consent to ${operator} processing the data below to create and operate my VLTone account, provide app access, restore access and protect the account. I give this choice by selecting a separate unchecked box and submitting registration, independently of accepting the terms.`),
      section("Data and operations", "Email, nickname, language, password hash, account ID, registration IP, consent revision and timestamp; account sessions and sign-ins; linked installation and device identifiers, device name, OS, app version and hardware information supplied on sign-in.", "Automated and mixed collection, recording, organisation, accumulation, storage, correction, retrieval, use for the stated purposes, restriction, deletion and destruction are permitted. Access is for the operator's authorised staff within their tasks. Public disclosure, marketing and optional diagnostics are excluded."),
      section("Duration and withdrawal", `Consent lasts until withdrawal or account closure, whichever occurs first. Email ${email} with “Withdraw consent”, your account email and request. Data no longer lawfully needed is removed within 30 days. Processing necessary for the agreement or another legal basis may continue; the operator identifies that basis in the response.`, "Without the required information and this consent, this registration form cannot create an account; public pages remain available. Removing data required to operate the account ends that access. Diagnostics require a separate choice."),
    ] },
    "diagnostics-consent": { intro: "An optional way to help fix VLTone. You can refuse without losing your account.", sections: [
      section("Purpose and choice", `I consent to ${operator} processing VLTone diagnostics to identify and fix errors, check compatibility and analyse performance. I make a separate choice during registration or in my account. Refusal does not block account creation, sign-in or core functions.`),
      section("Data and operations", "Account, installation and session IDs; version, OS and hardware; CPU/DSP, memory and audio settings; track and clip counts, playback state; track names, structure, routing, plugin names and versions; crash details and technical logs.", "Diagnostics are linked to the account. Normal telemetry excludes audio recordings, MIDI notes, passwords and plugin state blobs. Avoid personal information in track names and other diagnostic fields. Automated and mixed collection, recording, organisation, accumulation, storage, retrieval, use, restriction, deletion and destruction are permitted for the stated purposes. Access is limited to the operator's authorised specialists, with no public disclosure or marketing."),
      section("Retention and withdrawal", `Consent lasts until withdrawal or account closure. Each diagnostic record is kept for no more than 90 days from receipt. Withdraw in your account or email ${email} with “Disable diagnostics”. The server stops accepting new reports; existing data is deleted within 30 days unless another lawful basis applies. Withdrawal does not close your account.`),
    ] },
  };
  return documents[document];
}
