import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowUpRight, Braces, Layers3, Sparkles } from "lucide-react";
import { setRequestLocale } from "next-intl/server";
import { siteMetadata } from "@/lib/seo";
import { creatorNodes, portTypes } from "@/lib/creator/catalog";
import { AmbientMotionControl } from "@/components/ambient-motion-control";
import { TremoloDiagram } from "@/components/creator/tremolo-diagram";
import { PortExplorer } from "@/components/creator/port-explorer";
import { PortSymbol } from "@/components/creator/port-symbol";
import { SectionWires } from "@/components/creator/section-wires";
import { ModulationLab } from "@/components/creator/modulation-lab";
import { MemoryDemo } from "@/components/creator/memory-demo";
import { ProcessStages } from "@/components/creator/process-stages";
import type { Locale, PortType } from "@/lib/creator/types";

export async function generateMetadata({ params }: { params: Promise<{ locale: Locale }> }): Promise<Metadata> {
  const { locale } = await params;
  return siteMetadata(locale, "/creator", "Creator — VLTone", locale === "ru" ? "Создавай собственные эффекты в Creator: соединяй ноды, управляй модуляцией, пиши C++ и превращай идеи в мини-модули VLTone." : "Create your own effects in Creator: connect nodes, shape modulation, write C++ and turn ideas into VLTone mini-modules.");
}

const flowTypes: PortType[] = ["audio", "audio", "number", "number", "buffer", "array", "number", "function", "function", "gate", "audio", "audio"];
function Chapter({ id, number, tone, label, title, intro, children }: { id: string; number: number; tone: string; label: string; title: string; intro: string; children: React.ReactNode }) {
  return <section id={id} className="creator-chapter" data-tone={tone} data-output-type={flowTypes[number]} aria-labelledby={`${id}-title`}>
    <span className="creator-chapter-port" data-section-port="input" aria-hidden><PortSymbol type={flowTypes[number - 1]} size={24} /></span>
    <header className="creator-chapter-heading" data-reveal="0"><div className="creator-eyebrow"><span>{String(number).padStart(2, "0")}</span>{label}</div><h2 id={`${id}-title`}>{title}</h2><p>{intro}</p></header>
    {children}
    <span className="creator-chapter-port" data-section-port="output" aria-hidden><PortSymbol type={flowTypes[number]} size={24} /></span>
  </section>;
}

export default async function CreatorPage({ params }: { params: Promise<{ locale: Locale }> }) {
  const { locale } = await params; setRequestLocale(locale);
  const ru = locale === "ru";
  const docsLink = (slug: string, title: string) => <Link className="creator-text-link" href={`/creator/docs/guides/${slug}`}>{title}<ArrowUpRight size={17} aria-hidden /></Link>;
  return <main id="main-content" className="creator-page creator-theme" data-motion-root data-motion-paused="true" data-page-visible="false">
    <section className="studio-hero creator-hero" aria-labelledby="creator-title" data-motion-scene>
      <div className="hero-stage"><div className="hero-art" aria-hidden="true"><div className="hero-screen"><picture><source media="(max-width: 700px)" srcSet={`/images/creator/editor-${locale}-small.webp`} /><Image src={`/images/creator/editor-${locale}.webp`} width={3200} height={2000} alt="" loading="eager" fetchPriority="high" /></picture></div></div>
      <div className="studio-container hero-content"><div className="hero-editorial"><span className="creator-hero-label">VLTone Creator <span className="creator-new">SOON</span></span><h1 id="creator-title"><span>{ru ? "Создавай эффекты." : "Create effects."}</span><span>{ru ? "Соединяй идеи." : "Connect ideas."}</span></h1><div className="hero-copy-panel"><p>{ru ? "Твой звук начинается со связей. Собирай эффекты из нод, добавляй свою логику и C++ — и превращай схему в мини-модуль для VLTone." : "Your sound starts with connections. Build effects from nodes, add your own logic and C++ — and turn the graph into a VLTone mini-module."}</p><div className="hero-actions"><Link className="creator-button" href="/releases">{ru ? "Скачать VLTone" : "Download VLTone"}<ArrowDown size={17} aria-hidden /></Link><Link className="text-link" href="/creator/docs">{ru ? "Документация Creator" : "Creator documentation"}<ArrowUpRight size={17} aria-hidden /></Link></div></div></div></div></div>
      <div className="studio-container hero-motion-footer"><a className="creator-scroll-hint" href="#signal"><span className="creator-status-dot" />{ru ? "Проследи путь сигнала" : "Follow the signal"}<ArrowDown size={15} aria-hidden /></a></div>
    </section>
    <div className="creator-motion-dock"><AmbientMotionControl locale={locale} /></div>
    <div className="creator-stats studio-container"><div><strong>{creatorNodes.length}</strong><span>{ru ? "типов нод" : "node types"}</span></div><div><strong>8</strong><span>{ru ? "типов портов" : "port types"}</span></div><div><strong>2</strong><span>{ru ? "внешние ручки" : "external controls"}</span></div><div><strong>∞</strong><span>{ru ? "идей для звука" : "ideas for sound"}</span></div></div>

    <div className="creator-canvas"><div className="studio-container creator-story"><SectionWires />
      <Chapter id="signal" number={1} tone="coral" label={ru ? "ПУТЬ СИГНАЛА" : "SIGNAL PATH"} title={ru ? "Звук, который ты собрал сам." : "Sound you put together yourself."} intro={ru ? "Вход, обработка, выход. А между ними — твои решения. Вот Gentle Tremolo: шесть нод превращают обычный сигнал в ритмичную пульсацию." : "Input, processing, output. Your decisions connect them. Meet Gentle Tremolo: six nodes turn a simple signal into a rhythmic pulse."}>
        <TremoloDiagram locale={locale} />
        <div className="creator-detail-columns"><p>{ru ? "Раздели вход на две ветви. Одна сохранит исходный звук, другая пройдёт через Gain. LFO будет менять усиление во времени." : "Split the input into two branches. One preserves the original sound; the other passes through Gain. An LFO varies the gain over time."}</p><p>{ru ? "Соедини обе ветви в Mix. Ручка Depth определит, сколько обработанного сигнала попадёт в результат. Весь путь остаётся перед глазами." : "Bring both branches together in Mix. The Depth control determines how much processed signal reaches the result. The entire path stays visible."}</p></div>
        {docsLink("first-effect", ru ? "Собрать Gentle Tremolo по шагам" : "Build Gentle Tremolo step by step")}
      </Chapter>
      <Chapter id="ports" number={2} tone="lilac" label={ru ? "ТИПИЗИРОВАННЫЕ СВЯЗИ" : "TYPED CONNECTIONS"} title={ru ? "У каждого провода есть смысл." : "Every wire means something."} intro={ru ? "Звук, число, событие, функция. Цвет и форма порта подсказывают, что можно соединить. Выбери тип — и посмотри, какую задачу он решает." : "Sound, number, event, function. Port colors and shapes show what can connect. Choose a type to see what it does."}>
        <div className="creator-dark-demo creator-port-demo"><PortExplorer locale={locale} types={portTypes} /></div>
        <div className="creator-detail-columns"><p>{ru ? "Один выход может питать несколько входов. У каждого входа — один источник. Нужен другой тип? Добавь явный преобразователь, например Number to Integer." : "One output can feed several inputs. Each input has one source. Need another type? Add an explicit converter such as Number to Integer."}</p><p>{ru ? "Для Function важен не только тип, но и полная сигнатура. Для Array и List сначала выбери тип коллекции. Так схема остаётся понятной даже с десятками связей." : "Function needs an exact signature match as well as a matching type. For Array and List, choose the collection type first. The graph stays readable even with dozens of connections."}</p></div>
        {docsLink("ports", ru ? "Типы портов и правила соединений" : "Port types and connection rules")}
      </Chapter>
      <Chapter id="modulation" number={3} tone="lime" label={ru ? "МОДУЛЯЦИЯ" : "MODULATION"} title={ru ? "Параметры приходят в движение." : "Put your parameters in motion."} intro={ru ? "Любая ручка с числовым входом может получать сигнал. Пусть фильтр движется за огибающей, панорама — за LFO, а глубина эффекта — за твоей логикой." : "Any control with a numeric input can receive a signal. Let a filter follow an envelope, a parameter follow an LFO, and the effect depth follow your own logic."}>
        <ModulationLab locale={locale} />
        <div className="creator-detail-columns"><p>{ru ? "LFO даёт повторяемое движение, Random — меняющиеся значения, Sample & Hold — ступени. Выбирай форму и скорость под свою идею." : "LFO gives repeating motion, Random gives changing values, and Sample & Hold gives steps. Choose a shape and rate that fit your idea."}</p><p>{ru ? "Map Range согласует диапазоны, Clamp ограничит размах, Smooth смягчит скачки. Number обновляется на каждом сэмпле, а провод заменяет ручное значение." : "Map Range matches ranges, Clamp bounds the motion, and Smooth softens jumps. Number updates every sample, and a wire replaces the manual value."}</p></div>
        {docsLink("modulation", ru ? "От LFO до сложной модуляции" : "From an LFO to complex modulation")}
      </Chapter>
      <Chapter id="nodes" number={4} tone="blue" label={ru ? "БИБЛИОТЕКА НОД" : "NODE LIBRARY"} title={ru ? "Начни с готового. Собери своё." : "Start with the familiar. Make it yours."} intro={ru ? "113 типов нод — от готовых эффектов до элементарных операций. Собери цепочку за минуту или спустись до формул, фильтров и отдельных сэмплов." : "113 node types, from ready-made effects to elementary operations. Build a chain in minutes or go down to formulas, filters and individual samples."}>
        <div className="creator-family-grid">{[
          ["Effects", ru ? "Обработка" : "Effects", "Chorus · Delay · Compressor · EQ", ru ? "Смешивай готовые эффекты и управляй их параметрами." : "Combine effects and control their parameters."],
          ["Generators", ru ? "Источники звука" : "Sound sources", "Oscillator · Noise", ru ? "Создавай сигнал внутри схемы, выбирай форму и частоту." : "Generate a signal inside the graph; choose its shape and frequency."],
          ["Math", ru ? "Математика" : "Math", "Multiply · Map Range · Tanh", ru ? "Масштабируй, ограничивай и преобразуй управляющие значения." : "Scale, bound and transform control values."],
          ["Logic", ru ? "Условия" : "Conditions", "Compare · Select · Rising Edge", ru ? "Переключай ветви и реагируй на события." : "Switch branches and respond to events."],
          ["Analysis", ru ? "Анализ" : "Analysis", "Envelope · Peak · RMS", ru ? "Превращай уровень аудио в источник управления." : "Turn the audio level into a control source."],
          ["Filters", ru ? "Фильтры" : "Filters", "Biquad · FIR · One Pole", ru ? "Строй частотную обработку и задавай свои коэффициенты." : "Build frequency processing with your own coefficients."],
          ["Memory", ru ? "Память" : "Memory", "History · Delay Buffer · Context", ru ? "Храни состояние, строй задержки и учитывай темп проекта." : "Keep state, build delays and use the project tempo."],
          ["Collections", ru ? "Коллекции" : "Collections", "Array · List · Map · Reduce", ru ? "Работай с таблицами, массивами и их элементами." : "Work with tables, arrays and their elements."],
        ].map(([category, title, names, copy]) => <Link key={category} className="creator-family-node" href={`/creator/docs?category=${category}#catalog`}><h3>{title}<ArrowUpRight size={18} aria-hidden /></h3><code>{names}</code><p>{copy}</p></Link>)}</div>
        <Link className="creator-text-link" href="/creator/docs#catalog">{ru ? `Справочник всех ${creatorNodes.length} нод` : `Explore all ${creatorNodes.length} nodes`}<ArrowUpRight size={17} aria-hidden /></Link>
      </Chapter>
      <Chapter id="memory" number={5} tone="sand" label={ru ? "ПАМЯТЬ И ОБРАТНАЯ СВЯЗЬ" : "MEMORY & FEEDBACK"} title={ru ? "Схема умеет помнить." : "Give your graph a memory."} intro={ru ? "Накопление, счётчики, задержки, обратная связь. Для них нужно состояние: значение, которое остаётся после предыдущего сэмпла." : "Accumulation, counters, delays and feedback need state: a value that remains from the previous sample."}>
        <MemoryDemo locale={locale} />
        <div className="creator-detail-columns"><p>{ru ? "History хранит Number, Audio, Gate, Integer или коллекцию. Write enable позволяет удержать значение, Reset — начать заново. Мгновенный цикл без памяти редактор не пропустит." : "History stores a Number, Audio, Gate, Integer or collection. Write enable holds the value; Reset starts again. The editor rejects instantaneous cycles without memory."}</p><p>{ru ? "Для аудиозадержки используй Delay Buffer. Несколько Read Delay Tap могут читать одну память с разным временем задержки — основа для эха и многоголосной обработки." : "Use Delay Buffer for audio delay. Multiple Read Delay Tap nodes can read one memory at different times, providing a foundation for echoes and layered processing."}</p></div>
        {docsLink("ports", ru ? "Как правильно замкнуть обратную связь" : "How to connect a feedback path")}
      </Chapter>
      <Chapter id="custom" number={6} tone="mint" label={ru ? "СОБСТВЕННЫЕ НОДЫ" : "CUSTOM NODES"} title={ru ? "Большая идея. Один блок." : "A big idea. One block."} intro={ru ? "Выдели часть графа и преврати её в собственную ноду. Внутри остаются все соединения, снаружи — только выбранные порты. Используй результат снова и снова." : "Select part of a graph and turn it into your own node. Every connection stays inside; only the chosen ports remain outside. Reuse the result as often as you need."}>
        <div className="creator-feature-split"><div className="creator-feature-prose"><p>{ru ? "У каждого порта можно задать имя, тип, диапазон, единицы и значение по умолчанию. Двойной щелчок открывает внутреннюю схему, а вложенные ноды помогают держать большой проект в порядке." : "Give each port a name, type, range, unit and default. Double-click to open the inner graph; nested nodes keep a large project organized."}</p><p>{ru ? "Экземпляры разделяют определение, но хранят независимое состояние. Make independent создаёт отдельную версию. Для подходящих элементарных схем доступен oversampling 2× и 4×." : "Instances share a definition while keeping independent state. Make independent creates a separate version. Suitable elementary graphs can use 2× or 4× oversampling."}</p></div><div className="creator-nested-visual" data-motion-scene aria-hidden><div className="creator-nested-back loop-motion" /><div className="creator-nested-card"><span><Layers3 size={18} />My filter</span><div className="creator-mini-chain"><i>Input</i><b className="loop-motion">→</b><i>Biquad</i><b className="loop-motion">→</b><i>Output</i></div><footer>Audio in <span>2×</span> Audio out</footer></div></div></div>
        {docsLink("custom-nodes", ru ? "Вложенные схемы и oversampling" : "Nested graphs and oversampling")}
      </Chapter>
      <Chapter id="interface" number={7} tone="coral" label="INTERFACE" title={ru ? "Снаружи — только нужное." : "Only what you need on the outside."} intro={ru ? "Внутри может быть целая система. Снаружи — имя, две ручки и твой дизайн. Преврати техническую схему в инструмент, которым удобно пользоваться в проекте." : "There can be a whole system inside. Outside: a name, two controls and your design. Turn a technical graph into an instrument that feels at home in your project."}>
        <div className="creator-feature-split"><div className="creator-feature-prose"><p>{ru ? "В Gentle Tremolo первая ручка управляет Rate, вторая — Depth. Задай понятные диапазоны, единицы и defaults. Одна ручка может управлять несколькими параметрами." : "In Gentle Tremolo, the first control sets Rate and the second sets Depth. Define useful ranges, units and defaults. One control can drive several parameters."}</p><p>{ru ? "Настрой оформление карточки и до восьми режимов с общим управлением. Стабильные ID ручек сохраняют связь с автоматизацией при переименовании." : "Customize the card and up to eight modes with shared controls. Stable control IDs preserve automation when you rename a control."}</p></div><div className="creator-module-preview" data-motion-scene aria-label={ru ? "Пример оформления Gentle Tremolo" : "Gentle Tremolo appearance example"}><span className="creator-small-label">YOUR MODULE</span><strong>Gentle Tremolo</strong><div className="creator-knobs"><div><i className="creator-knob-rate loop-motion" /><span>Rate</span><code>1.8 Hz</code></div><div><i className="creator-knob-depth loop-motion" /><span>Depth</span><code>35%</code></div></div><footer><span className="creator-status-dot" />Main<span>Pre FX</span></footer></div></div>
        {docsLink("interface", ru ? "Оформление карточки и автоматизация" : "Card design and automation")}
      </Chapter>
      <Chapter id="code" number={8} tone="lilac" label="C++23 / SDK 1" title={ru ? "Твой алгоритм становится нодой." : "Your algorithm becomes a node."} intro={ru ? "Когда готовых блоков мало, добавь C++ Function. Напиши обработку, обнови ноду — Creator создаст порты по сигнатуре функции." : "When the built-in blocks are not enough, add a C++ Function. Write your processing and update the node: Creator derives its ports from the function signature."}>
        <div className="creator-code-demo creator-dark-demo" data-motion-scene><div className="creator-lab-top"><span><Braces size={18} aria-hidden />process.cpp</span><code>C++23</code></div><pre><code>{"#include <vlt/creator.hpp>\n\nvlt::AudioFrame process(vlt::AudioFrame audio,\n                        float gain = 0.5f) {\n    return {audio.left * gain,\n            audio.right * gain};\n}"}</code></pre><div className="creator-code-ports"><span><PortSymbol type="audio" />audio</span><i className="loop-motion" /><span><PortSymbol type="number" />gain</span><i className="loop-motion" /><span><PortSymbol type="function" />process()</span></div></div>
        <div className="creator-detail-columns"><p>{ru ? "AudioFrame, float и bool превращаются в Audio, Number и Gate. Структура результата может дать несколько выходов, а Function-порт позволяет вызывать другую C++-ноду из своего кода." : "AudioFrame, float and bool become Audio, Number and Gate. A result struct can expose several outputs; a Function port lets your code call another C++ node."}</p><p>{ru ? "SDK описывает состояние, подготовку, сброс, latency и tail. Память готовится заранее, чтобы обработка работала в реальном времени. После изменения сигнатуры обнови порты." : "The SDK describes state, preparation, reset, latency and tail. Prepare memory in advance for realtime processing. Refresh the ports whenever the signature changes."}</p></div>
        {docsLink("cpp", ru ? "Код, сигнатуры и Creator SDK" : "Code, signatures and the Creator SDK")}
      </Chapter>
      <Chapter id="ai" number={9} tone="lime" label="CREATOR ASSISTANT" title={ru ? "Начни с описания звука." : "Start by describing the sound."} intro={ru ? "Расскажи помощнику, что ты хочешь услышать. Он работает в контексте открытого Creator: читает граф, меняет ноды, редактирует C++ и помогает со сборкой." : "Tell the assistant what you want to hear. It works in the context of the open Creator: reading the graph, changing nodes, editing C++ and helping with compilation."}>
        <blockquote className="creator-ai-prompt"><Sparkles size={23} aria-hidden /><p>{ru ? "«Собери мягкий тремоло. Первая ручка — скорость, вторая — глубина. Проверь соединения и скомпилируй»." : "“Build a gentle tremolo. The first control is rate, the second is depth. Check the connections and compile.”"}</p></blockquote>
        <ProcessStages locale={locale} label={ru ? "Пример последовательности работы" : "Example workflow"} steps={[
          { title: ru ? "Контекст" : "Context", code: "Input → Graph → Output", detail: ru ? "Помощник получает описание проекта и доступных нод. Укажи характер эффекта, нужные ручки и ограничения." : "The assistant receives the project and available node descriptions. Specify the sound, controls and constraints." },
          { title: ru ? "Изменения" : "Edits", code: "LFO → Gain · Interface → Rate / Depth", detail: ru ? "Изменения появляются в реальном графе. Можно уточнить запрос, посмотреть связи и продолжить редактирование самостоятельно." : "Changes appear in the actual graph. Refine the request, inspect the wires or continue editing yourself." },
          { title: ru ? "Проверка" : "Validation", code: "Validate → Compile → Audition", detail: ru ? "Помощник может проверить схему и запустить компиляцию. Результат прослушивается в VLTone; историю изменений можно откатить." : "The assistant can validate the graph and compile it. Audition the result in VLTone; edits remain available in undo history." },
        ]} />
        {docsLink("ai", ru ? "Возможности и настройка AI-помощника" : "AI assistant capabilities and setup")}
      </Chapter>
      <Chapter id="compile" number={10} tone="sand" label={ru ? "ИЗ СХЕМЫ В ЭФФЕКТ" : "FROM GRAPH TO EFFECT"} title={ru ? "Соедини. Собери. Используй." : "Connect. Compile. Make music."} intro={ru ? "Сохрани исходную схему, нажми Compile и добавь свой мини-модуль в Channel Strip. Когда идея изменится, обнови тот же модуль." : "Save the source graph, press Compile and add your mini-module to Channel Strip. When your idea changes, update the same module."}>
        <ProcessStages locale={locale} label={ru ? "От проекта до мини-модуля" : "From project to mini-module"} steps={[
          { title: ru ? "Сохрани" : "Save", code: ".vltcreator", detail: ru ? "Исходный проект хранит граф, расположение нод, режимы и код. Открывай его, когда нужно изменить эффект." : "The source project stores the graph, node layout, modes and code. Open it whenever you want to change the effect." },
          { title: "Compile", code: "Ports → Graph → DSP", detail: ru ? "Проверяются типы, обязательные входы и допустимость графа. Ошибка указывает на проблемное место; предыдущая работающая версия сохраняется." : "Types, required inputs and graph validity are checked. Errors identify the problem; the previous working version is preserved." },
          { title: "VLTone", code: ".vltmini → Channel Strip", detail: ru ? "Установи скомпилированный модуль и выбери его в Channel Strip. Проверь звук, параметры и режимы на своём материале." : "Install the compiled module and select it in Channel Strip. Check its sound, controls and modes on your own material." },
        ]} />
        <p className="creator-feature-note">{ru ? "Валидация помогает найти несовместимые порты, неподключённые входы и циклы без памяти до прослушивания. Для C++ также доступны сообщения компилятора с указанием строки." : "Validation catches incompatible ports, missing inputs and cycles without memory before auditioning. C++ also provides compiler diagnostics with source locations."}</p>
        {docsLink("files", ru ? "Сохранение, установка и обновление" : "Saving, installing and updating")}
      </Chapter>
      <Chapter id="share" number={11} tone="blue" label={ru ? "ПОВТОРНОЕ ИСПОЛЬЗОВАНИЕ" : "REUSE & SHARING"} title={ru ? "Хорошие идеи остаются с тобой." : "Keep your good ideas close."} intro={ru ? "Сохраняй целые эффекты и небольшие полезные блоки. Передавай готовый результат или редактируемую схему — для каждой задачи есть свой формат." : "Save complete effects and small useful building blocks. Share the finished result or the editable graph: each task has its own format."}>
        <div className="creator-share-formats"><article><code>.vltcreator</code><h3>{ru ? "Продолжить работу" : "Keep creating"}</h3><p>{ru ? "Проект с раскладкой, кодом и режимами. Для себя, соавтора или следующей версии эффекта." : "A project with its layout, code and modes. For yourself, a collaborator or the next version."}</p></article><article><code>.vltnode</code><h3>{ru ? "Повторить удачный блок" : "Reuse a useful block"}</h3><p>{ru ? "Собственная нода и её зависимости. Импортируй в другой проект Creator и подключай к новым идеям." : "A custom node and its dependencies. Import it into another Creator project and connect it to new ideas."}</p></article><article><code>.vltmini</code><h3>{ru ? "Использовать эффект" : "Use the effect"}</h3><p>{ru ? "Скомпилированный мини-модуль для установки в VLTone и работы в Channel Strip." : "A compiled mini-module to install in VLTone and use in Channel Strip."}</p></article></div>
        <a className="creator-example-download" href="/creator/downloads/Gentle-Tremolo.vltcreator" download><span><strong>{ru ? "Начни с Gentle Tremolo" : "Start with Gentle Tremolo"}</strong><small>{ru ? "Тот самый проект из примеров — открой и измени его под себя." : "The actual project from these examples. Open it and make it your own."}</small></span><ArrowDown size={23} aria-hidden /></a>
        {docsLink("files", ru ? "Подробнее о форматах и обмене" : "More about formats and sharing")}
      </Chapter>
    </div></div>
    <section className="creator-bottom-cta"><div className="studio-container"><span className="creator-eyebrow">NEXT CONNECTION: YOU</span><h2>{ru ? "Теперь соедини" : "Now connect"}<br /><em>{ru ? "свою идею." : "your idea."}</em></h2><div className="hero-actions"><Link className="creator-button" href="/releases">{ru ? "Скачать VLTone" : "Download VLTone"}<ArrowDown size={18} aria-hidden /></Link><Link className="creator-text-link" href="/creator/docs">{ru ? "Открыть документацию" : "Open documentation"}<ArrowUpRight size={18} aria-hidden /></Link></div></div></section>
  </main>;
}
