import { l, type Guide } from "./types";

export const guides: Guide[] = [
  { slug: "first-effect", title: l("Первый эффект: Gentle Tremolo", "Your first effect: Gentle Tremolo"), intro: l("Собери тремоло с двумя ручками: скоростью колебаний и глубиной эффекта.", "Build a tremolo with two controls: modulation rate and effect depth."), sections: [
    { id: "start", title: l("Открой Creator", "Open Creator"), steps: [l("В VLTone открой Вид → Creator и создай новый проект. Input, Output и Interface уже находятся на полотне.", "In VLTone, open View → Creator and create a new project. Input, Output and Interface are already on the canvas."), l("Через библиотеку или Tab добавь Gain, Mix и LFO. Размести аудионоды слева направо, LFO и Interface — ниже.", "Use the library or Tab to add Gain, Mix and LFO. Arrange the audio nodes from left to right, with LFO and Interface below.")] },
    { id: "connect", title: l("Соедини две ветви", "Connect the two branches"), diagram: true, steps: [l("Input / Output → Gain / Audio. Gain / Output → Mix / B.", "Input / Output → Gain / Audio. Gain / Output → Mix / B."), l("Input / Output → Mix / A: это сухая ветвь. Mix / Output → Output / Audio.", "Input / Output → Mix / A is the dry branch. Mix / Output → Output / Audio."), l("LFO / Output → Gain / Gain. Поставь LFO: Sine, Rate 1.8 Hz, Amount 0.5, Offset 0.5. Усиление будет меняться от 0 до 1.", "LFO / Output → Gain / Gain. Set LFO to Sine, Rate 1.8 Hz, Amount 0.5, Offset 0.5. Gain will move between 0 and 1.")], links: ["input", "gain", "mix", "lfo"] },
    { id: "controls", title: l("Выведи управление наружу", "Expose the controls"), steps: [l("Выбери Interface. Назови модуль Gentle Tremolo. Первая ручка: Rate, единицы Hz, диапазон 0.1–10, default 1.8, логарифмическая шкала.", "Select Interface. Name the module Gentle Tremolo. First control: Rate, unit Hz, range 0.1–10, default 1.8, logarithmic scale."), l("Вторая ручка: Depth, диапазон 0–1, default 0.35. Rate → LFO / Rate, Depth → Mix / Mix.", "Second control: Depth, range 0–1, default 0.35. Rate → LFO / Rate, Depth → Mix / Mix."), l("Сохрани .vltcreator и нажми Compile. Добавь установленный мини-модуль в Channel Strip и прослушай его. Depth = 0 оставляет сухой сигнал.", "Save the .vltcreator and press Compile. Add the installed mini-module to a Channel Strip and audition it. Depth = 0 keeps the dry signal.")], links: ["interface", "output"] },
  ] },
  { slug: "editor", title: l("Управление редактором", "Working in the editor"), intro: l("Добавление нод, соединения, навигация, история и сохранение проекта.", "Adding nodes, wiring, navigation, history and project files."), sections: [
    { id: "nodes", title: l("Добавление и выделение", "Adding and selecting"), paragraphs: [l("Найди ноду в библиотеке и добавь двойным щелчком. Tab на полотне открывает поиск. Перетаскивай ноду за заголовок; рамка выделения позволяет работать с группой.", "Find a node in the library and double-click to add it. Tab on the canvas opens search. Drag a node by its header; marquee-select to work with a group."), l("Copy/Paste сохраняет внутренние связи выделенной группы, создавая новые ID. Duplicate делает копию. Delete удаляет выбранные ноды или провода; базовые Input, Output и Interface защищены.", "Copy/Paste preserves a group’s internal wires while creating new IDs. Duplicate makes a copy. Delete removes selected nodes or wires; the base Input, Output and Interface nodes are protected.")] },
    { id: "wires", title: l("Соединения и параметры", "Connections and parameters"), paragraphs: [l("Перетаскивай выход на совместимый вход. В свойствах выбранной ноды можно выбрать источник из списка — это также способ подключения с клавиатуры.", "Drag an output onto a compatible input. The selected node’s properties also let you choose an input source from a list, providing a keyboard alternative."), l("Когда к параметру подключён провод, входящий поток заменяет его ручное значение. После отключения возвращается сохранённое ручное значение.", "A connected parameter uses the incoming stream in place of its manual value. Disconnecting restores the stored manual value.")] },
    { id: "navigation", title: l("Перемещение и история", "Navigation and history"), paragraphs: [l("Средняя кнопка мыши или Space + drag перемещает полотно. Ctrl (Cmd на macOS) + колесо меняет масштаб вокруг указателя в пределах 25–250%. F вписывает граф, Ctrl/Cmd+0 возвращает 100%.", "Middle-drag or Space + drag pans the canvas. Ctrl (Cmd on macOS) + wheel zooms around the pointer from 25–250%. F fits the graph; Ctrl/Cmd+0 restores 100%."), l("Сохранение, Undo/Redo и буфер обмена используют платформенные сочетания: Ctrl в Windows и Cmd на macOS. Compile — Ctrl+Enter (Cmd+Enter на macOS). История Creator отделена от истории проекта DAW.", "Save, Undo/Redo and clipboard actions use platform shortcuts: Ctrl on Windows and Cmd on macOS. Compile is Ctrl+Enter (Cmd+Enter on macOS). Creator history is separate from DAW project history."), l("Восстановление черновика предлагается в стартовом окне. Закрытие изменённого проекта предлагает сохранить, отбросить или отменить закрытие.", "Draft recovery is offered in the welcome window. Closing an edited project offers Save, Discard or Cancel.")] },
  ] },
  { slug: "ports", title: l("Порты и соединения", "Ports and connections"), intro: l("Тип, форма и цвет объясняют, что проходит по проводу. Типы не преобразуются автоматически.", "Type, shape and color describe what a wire carries. Types are not converted automatically."), sections: [
    { id: "types", title: l("Восемь типов", "Eight types"), paragraphs: [l("Audio — mono/stereo звук; Number — числовой поток; Gate — логическое состояние; Integer — целое число. Array и List передают коллекции чисел. Buffer передаёт ссылку на память задержки. Function связывает вызываемые C++-функции.", "Audio carries mono/stereo sound; Number is a numeric stream; Gate is a logical state; Integer is an integer. Array and List carry number collections. Buffer references delay storage. Function binds callable C++ functions.")], links: ["audio_to_number", "number_to_audio", "number_to_integer", "integer_to_number", "gate_to_number", "number_to_gate"] },
    { id: "rules", title: l("Что можно соединить", "What can connect"), paragraphs: [l("Соединяй выход и вход одного типа. Один выход может питать несколько входов, но у каждого входа только один источник. Для Function дополнительно должна совпасть полная сигнатура.", "Connect an output and input of the same type. One output may feed multiple inputs, but each input has only one source. Function ports additionally require an exact signature match."), l("Array и List — разные типы. В нодах, поддерживающих оба, сначала выбери нужный тип коллекции в свойствах. Number и Integer соединяются через преобразователи.", "Array and List are different types. For nodes supporting both, choose the collection type in properties first. Connect Number and Integer through converters."), l("Обязательные входы участвующих в обработке нод должны быть подключены. Неиспользуемые ветви можно оставить в проекте — они не исполняются.", "Required inputs of nodes used by the processing graph must be connected. Unused branches may remain in the project; they are not executed.")] },
    { id: "feedback", title: l("Обратная связь", "Feedback"), paragraphs: [l("Цикл без памяти отклоняется. History отдаёт предыдущее значение до записи Next; Delay Buffer и Read Delay Tap обеспечивают явную задержку. Named Value сам по себе цикл не разрывает.", "A cycle without memory is rejected. History outputs its previous value before committing Next; Delay Buffer and Read Delay Tap provide explicit delay. Named Value alone does not break a cycle."), l("Рекурсивные зависимости Function запрещены. Buffer и Function не могут пересекать границу oversampling.", "Recursive Function dependencies are forbidden. Buffer and Function cannot cross an oversampling boundary.")], links: ["history", "delay_buffer", "delay_read", "wire"] },
  ] },
  { slug: "modulation", title: l("Модуляция и анализ", "Modulation and analysis"), intro: l("Пусть параметры следуют времени, огибающей сигнала или твоим внешним ручкам.", "Make parameters follow time, the signal envelope or your external controls."), sections: [
    { id: "range", title: l("Согласуй диапазоны", "Match the ranges"), paragraphs: [l("LFO по умолчанию выдаёт −1…1. Для Gain 0…1 поставь Amount 0.5, Offset 0.5. Для частоты фильтра используй Map Range. Clamp явно ограничивает результат.", "The default LFO outputs −1…1. For Gain 0…1, use Amount 0.5 and Offset 0.5. Use Map Range for filter frequency and Clamp to explicitly bound the result."), l("Параметры с входом Number можно модулировать. Переключатели, формы и размеры памяти без такого входа задаются статически.", "Parameters with a Number input can be modulated. Switches, shapes and memory sizes without such an input are static.")], diagram: true, links: ["lfo", "map_range", "clamp"] },
    { id: "follow", title: l("Управляй звуком от звука", "Control sound with sound"), paragraphs: [l("Envelope Follower преобразует уровень Audio в Number с Attack/Release. Peak Detector измеряет мгновенный пик; Window RMS — среднюю энергию в окне. Audio to Number извлекает сам сэмпл и не заменяет измеритель уровня.", "Envelope Follower turns Audio level into a Number with Attack/Release. Peak Detector measures instantaneous peaks; Window RMS measures windowed energy. Audio to Number extracts a sample and is not a level detector."), l("Smooth, Attack / Release и Slew Limiter помогают управлять скоростью изменений. Sample & Hold запоминает значение по фронту Gate.", "Smooth, Attack / Release and Slew Limiter control how quickly values change. Sample & Hold captures a value on a rising Gate edge.")], links: ["envelope", "peak", "window_rms", "smooth", "sample_hold"] },
  ] },
  { slug: "interface", title: l("Карточка, ручки и режимы", "Card, controls and modes"), intro: l("Преврати схему в компактный мини-модуль для Channel Strip.", "Turn your graph into a compact Channel Strip mini-module."), sections: [
    { id: "card", title: l("Оформление", "Appearance"), paragraphs: [l("Выбери Interface: задай имя модуля, материал карточки, фон или изображение и вид ручек. Предпросмотр использует ту же карточку, что и Channel Strip. Изображение встраивается в файл модуля.", "Select Interface to set the module name, card material, background color or image and control appearance. The preview uses the same card as Channel Strip. Images are embedded in the module file.")] },
    { id: "controls", title: l("Две внешние ручки", "Two external controls"), paragraphs: [l("У ручки есть стабильный ID, имя, единицы, минимум, максимум, default, линейная или логарифмическая шкала и оформление. Для логарифмической шкалы минимум должен быть положительным.", "Each control has a stable ID, name, unit, minimum, maximum, default, linear or logarithmic scale and appearance. A logarithmic minimum must be positive."), l("Выход Number можно разветвлять на несколько нод. Сохраняй ID при переименовании: он связывает ручку с автоматизацией в проекте.", "Its Number output can fan out to multiple nodes. Preserve the ID when renaming: it binds the control to project automation.")], links: ["interface", "map_range"] },
    { id: "modes", title: l("До восьми режимов", "Up to eight modes"), paragraphs: [l("Режимы содержат разные графы с общими ручками и оформлением. Новый режим копирует текущий граф. Compile проверяет все режимы, включая невыбранные.", "Modes contain different graphs with shared controls and appearance. A new mode copies the current graph. Compile validates every mode, including inactive ones.")] },
  ] },
  { slug: "custom-nodes", title: l("Собственные ноды и коллекции", "Custom nodes and collections"), intro: l("Собирай повторно используемые блоки, открывай их внутренний граф и делись .vltnode.", "Build reusable blocks, open their internal graphs and share .vltnode files."), sections: [
    { id: "group", title: l("Упакуй схему", "Package a graph"), paragraphs: [l("Выдели обрабатывающие ноды и выбери создание собственной ноды. Пересекающие границу провода превращаются в именованные порты. Группа должна иметь выход наружу; Input, Output и Interface внутрь не упаковываются.", "Select processing nodes and create a custom node. Wires crossing the boundary become named ports. The group needs an outgoing connection; Input, Output and Interface are not packed inside."), l("Открой собственную ноду двойным щелчком. Изменение определения обновляет его экземпляры; Make independent создаёт отдельную копию типа. Экспорт .vltnode включает вложенные определения и расположение нод.", "Double-click to open a custom node. Editing the definition updates its instances; Make independent creates a separate type. Exporting .vltnode includes nested definitions and node positions.")], links: ["subgraph", "subgraph_input", "subgraph_output"] },
    { id: "oversampling", title: l("Oversampling", "Oversampling"), paragraphs: [l("Выбирай 1×, 2× или 4× для внутренней схемы. 2×/4× полезны для нелинейной обработки и создают явную границу частоты дискретизации. Перед разворачиванием ноды верни 1×.", "Choose 1×, 2× or 4× for the internal graph. 2×/4× is useful for nonlinear processing and creates an explicit sample-rate boundary. Return to 1× before expanding the node."), l("Внутри oversampling и тел Map/Reduce поддерживаются элементарные ноды. Готовые Effects, Reverb и C++ Function не допускаются в таких телах; Function и Buffer не пересекают границу частоты.", "Oversampled graphs and Map/Reduce bodies support elementary nodes. Built-in Effects, Reverb and C++ Function are not allowed in these bodies; Function and Buffer cannot cross a rate boundary.")], links: ["hard_clip", "biquad", "dc_block"] },
    { id: "collections", title: l("Array, List, Map и Reduce", "Array, List, Map and Reduce"), paragraphs: [l("Array имеет фиксированную длину; List меняет длину в пределах Capacity. Get/Set используют индексы от 0. Модифицирующие ноды возвращают новую коллекцию; History сохраняет результат между сэмплами.", "Array has a fixed length; List changes length within Capacity. Get/Set use zero-based indices. Editing nodes return a new collection; History retains the result between samples."), l("Подграф Map требует входы с ID item:Number и index:Integer, один выход Number. Reduce дополнительно требует accumulator:Number. ID здесь значимы. Тело создаётся вместе с нодой; открой его двойным щелчком или кнопкой Open node. Это не Function-провод.", "A Map subgraph requires inputs with IDs item:Number and index:Integer, and one Number output. Reduce additionally requires accumulator:Number. These IDs matter. The body is created with the node; double-click or choose Open node to edit it. This is not a Function wire.")], links: ["array", "list", "map", "reduce", "history"] },
    { id: "limits", title: l("Ограничения графа", "Graph limits"), paragraphs: [l("Текущий формат поддерживает до 512 нод и 2048 соединений с учётом разворачивания, восемь уровней вложенности, 16 портов на сторону собственной ноды, коллекции до 4096 элементов и до 16 MiB подготовленной памяти DSP.", "The current format supports up to 512 nodes and 2048 connections after expansion, eight nesting levels, 16 ports per custom-node side, collections up to 4096 elements and 16 MiB of prepared DSP storage.")] },
  ] },
  { slug: "cpp", title: l("C++ и Creator SDK", "C++ and the Creator SDK"), intro: l("Добавляй собственные алгоритмы и вызываемые функции с переносимым SDK 1 для C++23.", "Add your own algorithms and callable functions with portable SDK 1 for C++23."), sections: [
    { id: "function", title: l("Первая функция", "Your first function"), paragraphs: [l("Добавь C++ Function. Укажи Entry function = process, вставь код и нажми «Обновить ноду». Анализ исходника создаст реальные порты. Подключи Audio и результат, затем Compile.", "Add a C++ Function. Set Entry function to process, enter the code and choose Update node. Source analysis creates the actual ports. Connect Audio and the result, then Compile.")], code: "#include <vlt/creator.hpp>\n\nvlt::AudioFrame process(vlt::AudioFrame audio, float gain = 0.5f) {\n    return {audio.left * gain, audio.right * gain};\n}", links: ["cpp_function", "input", "output"] },
    { id: "signature", title: l("Сигнатура и порты", "Signature and ports"), paragraphs: [l("float становится Number, bool — Gate, vlt::AudioFrame — Audio. Возвращаемая структура может создавать несколько выходов. VLT_PORT задаёт стабильный ID; значения по умолчанию задают ручные значения числовых входов.", "float becomes Number, bool becomes Gate and vlt::AudioFrame becomes Audio. A returned struct can create multiple outputs. VLT_PORT assigns stable IDs; default arguments define manual values for numeric inputs."), l("vlt::Function<Signature> создаёт вызываемый вход. Подключи Function-выход другой C++-ноды с той же сигнатурой. Это вызов с аргументами из кода, а не готовый аудиопоток. Каждый binding хранит собственное состояние.", "vlt::Function<Signature> creates a callable input. Connect another C++ node’s Function output with the same signature. This is a call with code-provided arguments, not a precomputed audio stream. Each binding has its own state.")] },
    { id: "state", title: l("Состояние и realtime", "State and realtime"), paragraphs: [l("Состояние хранится в State. Подготавливай vlt::Buffer в prepare, очищай историю в reset. Во время process не выделяй память, не работай с файлами, сетью или ОС. Локальные helpers помещай в тот же исходник либо в другую Function-ноду.", "Keep persistent data in State. Prepare vlt::Buffer in prepare and clear history in reset. Do not allocate memory or access files, networks or the OS in process. Put local helpers in the same source or another Function node."), l("Контекст передаёт частоту дискретизации, время, темп и seed. Корректно объявляй latency и tail для выравнивания параллельных ветвей и завершения экспорта.", "The context provides sample rate, time, tempo and seed. Declare latency and tail correctly for parallel-path alignment and export completion.")] },
    { id: "build", title: l("Проверка и сборка", "Validation and compilation"), paragraphs: [l("После любой правки, даже тела функции без изменения сигнатуры, нажми «Обновить ноду». Это анализ исходника, а не публикация нового DSP. Compile проверяет графы, собирает переносимый код и устанавливает .vltmini.", "After every source edit, even a body-only change, choose Update node. This analyzes source; it does not publish new DSP. Compile checks the graphs, builds portable code and installs a .vltmini."), l("Проверь mono/stereo, крайние параметры, разные частоты дискретизации, reset, автоматизацию и хвост эффекта. Успешная компиляция сама по себе не оценивает звук.", "Check mono/stereo, extreme parameter values, different sample rates, reset, automation and effect tails. Successful compilation does not by itself assess the sound.")] },
  ] },
  { slug: "ai", title: l("AI-помощник Creator", "Creator AI assistant"), intro: l("Помощник работает с графом, исходниками и сборкой прямо в редакторе.", "The assistant works with graphs, source code and builds directly in the editor."), sections: [
    { id: "connect", title: l("Подключение", "Connection"), paragraphs: [l("Открой Assistant в панели Creator. Модели, аккаунт, ключи и учёт использования общие с основным чатом VLTone; выбор модели Creator независим. Настрой подключение через шестерёнку.", "Open Assistant in the Creator toolbar. Models, account, keys and usage are shared with the main VLTone chat; Creator’s model selection is independent. Configure the connection with the gear button.")] },
    { id: "request", title: l("Поставь задачу", "Describe the task"), paragraphs: [l("«Собери тремоло нодами: первая ручка — скорость 0.1–10 Hz, вторая — глубина 0–1. Проверь и скомпилируй». Помощник видит текущий граф, режим, подграф и выделение, читает SDK, меняет ноды и C++, проверяет порты и собирает модуль.", "“Build a tremolo with nodes: the first control is rate from 0.1–10 Hz, the second is depth from 0–1. Validate and compile it.” The assistant sees the current graph, mode, subgraph and selection, reads the SDK, edits nodes and C++, checks ports and builds the module."), l("Для объяснения без правок укажи это прямо. Проверка подтверждает корректность графа и готовность DSP; звук и художественный результат оцениваешь ты.", "Explicitly ask for an explanation without edits when that is your intent. Validation confirms graph correctness and DSP preparation; you assess the sound and creative result.")] },
    { id: "undo", title: l("Остановка и откат", "Stopping and reverting"), paragraphs: [l("Stop отменяет текущий запрос и фоновую работу; уже внесённые правки остаются в черновике. Последовательные правки AI объединяются в Undo, а ручные правки остаются отдельными.", "Stop cancels the current request and background work; edits already made remain in the draft. Consecutive AI edits form one Undo operation; manual edits stay separate."), l("«Отменить результат AI» восстанавливает последний результат вместе с установленным модулем и затронутыми экземплярами, если после него не возник конфликт. Контрольная точка доступна в текущем сеансе.", "Revert AI result restores the last result together with its installed module and affected instances if no conflicting changes occurred afterward. The checkpoint is available in the current session."), l("Переписка хранится локально для модуля. История и ключи не включаются в .vltcreator, .vltmini или публикуемый модуль.", "Conversations are stored locally per module. History and keys are not included in .vltcreator, .vltmini or published modules.")] },
  ] },
  { slug: "files", title: l("Файлы, Compile и установка", "Files, Compile and installation"), intro: l("Редактируемый проект, собственная нода и готовый мини-модуль решают разные задачи.", "An editable project, a custom node and an installed mini-module serve different purposes."), sections: [
    { id: "formats", title: l("Три формата", "Three formats"), paragraphs: [l(".vltcreator v3 — редактируемый проект: графы, C++, режимы, расположение нод и состояние редактора. Читаются версии 1–2. Сохранять можно и незавершённую схему.", ".vltcreator v3 is the editable project: graphs, C++, modes, node layout and editor state. Versions 1–2 remain readable. Incomplete graphs can also be saved."), l(".vltnode v1 — собственная нода с вложенными определениями для импорта в другие схемы. При конфликте определения можно обновить тип проекта или импортировать независимую копию.", ".vltnode v1 is a custom node with nested definitions for reuse in other graphs. A conflicting definition can update the project’s type or be imported as an independent copy."), l(".vltmini v5 — переносимый готовый мини-модуль для VLTone. Это результат Compile, включая оформление; это не VST-бинарник. Чтение старых форматов сохраняется.", ".vltmini v5 is a portable ready-to-use VLTone mini-module. Compile produces it with the card appearance; it is not a VST binary. Older formats remain readable.")] },
    { id: "compile", title: l("Сборка и использование", "Building and using"), paragraphs: [l("Compile проверяет все режимы и актуальность C++-портов, подготавливает DSP в фоне и атомарно устанавливает файл в Documents/VLTONE/MiniModules. Добавь его через библиотеку мини-модулей Channel Strip.", "Compile validates every mode and C++ port freshness, prepares DSP in the background and atomically installs the file in Documents/VLTONE/MiniModules. Add it through the Channel Strip mini-module library."), l("Передай .vltmini другому пользователю: он может импортировать файл через стойку или поместить его в свою папку MiniModules. Для редактирования передавай также .vltcreator.", "Share the .vltmini: the recipient can import it through the rack or place it in their MiniModules folder. Include the .vltcreator when sharing editable source.")] },
    { id: "updates", title: l("Повторная компиляция", "Recompiling"), paragraphs: [l("Стабильный ID модуля позволяет обновить совпадающие экземпляры открытого проекта, включая Master, сохранив размещение, bypass и совместимые значения ручек. Закрытые проекты сохраняют встроенные определения.", "A stable module ID lets recompilation update matching instances in the open project, including Master, preserving placement, bypass and compatible control values. Closed projects retain their embedded definitions."), l("Активный экспорт или Freeze откладывает применение. Ошибочная сборка не заменяет работающий файл и DSP. Undo исходника не публикует старый звук: для этого снова скомпилируй нужное состояние.", "Active export or Freeze defers application. A failed build does not replace the working file or DSP. Undoing source edits does not publish an older sound: compile the desired state again.")] },
  ] },
  { slug: "troubleshooting", title: l("Диагностика ошибок", "Troubleshooting"), intro: l("Начинай с первой ошибки: восстанови порты и связи, затем повтори проверку.", "Start with the first error: repair ports and connections, then validate again."), sections: [
    { id: "wiring", title: l("Ошибки соединений", "Connection errors"), paragraphs: [l("Incompatible port types: сравни типы обоих концов, добавь явный преобразователь. Input already connected: сначала отключи прежний источник. Unknown port: проверь ID и актуальность портов C++ или собственной ноды.", "Incompatible port types: compare both endpoint types and add an explicit converter. Input already connected: disconnect the previous source first. Unknown port: check IDs and refresh C++ or custom-node ports."), l("Connect required input: подключи все обязательные входы используемой ветви. Feedback cycle: разорви мгновенный цикл явной History или Delay Buffer. Function recursive cycle: убери рекурсивный вызов.", "Connect required input: connect every required input of the active branch. Feedback cycle: break the instantaneous cycle with explicit History or Delay Buffer. Function recursive cycle: remove the recursive call.")], links: ["history", "delay_buffer", "cpp_function"] },
    { id: "cpp", title: l("Ошибки C++", "C++ errors"), paragraphs: [l("Update C++ function ports / Function ports changed: нажми «Обновить ноду» после изменения исходника. Проверь Entry function и допустимые типы. Строка и столбец диагностики ведут к месту ошибки.", "Update C++ function ports / Function ports changed: choose Update node after changing source. Check Entry function and supported types. Diagnostic line and column numbers locate the error."), l("allocation outside prepare: перенеси подготовку Buffer в prepare. Incompatible function binding: сверь полную сигнатуру Function, включая возвращаемые значения и порядок аргументов.", "allocation outside prepare: move Buffer allocation to prepare. Incompatible function binding: check the full Function signature, including return values and argument order.")] },
    { id: "sound", title: l("Нет ожидаемого результата", "The result is not as expected"), paragraphs: [l("Проверь связь с Output, ручки Interface, выбранный режим, dry/wet, bypass и наличие входного аудио. Убедись, что Compile завершился и экземпляр получил обновление. Слишком малая модуляция часто означает несогласованные диапазоны.", "Check the Output connection, Interface controls, selected mode, dry/wet, bypass and incoming audio. Confirm that Compile completed and the instance received the update. Weak modulation often means mismatched ranges."), l("Проверь ограничения памяти, длину коллекций и коэффициенты фильтров. Схемы с C++ или готовыми Effects нельзя помещать в тела Map/Reduce или oversampling.", "Check memory limits, collection lengths and filter coefficients. Graphs containing C++ or built-in Effects cannot be used as Map/Reduce or oversampling bodies.")] },
  ] },
];
export const findGuide = (slug: string) => guides.find(guide => guide.slug === slug);
