import { l, type Localized } from "./types";

export type NodeSetting = { name: string; value: Localized; detail: Localized };
const collectionNodes = new Set(["length", "get", "set", "clear", "sum", "collection_min", "collection_max", "map", "reduce"]);

// Structural properties come from NodeDefinition, makeNode and programmingProperties.
// They are configured before compilation and cannot be modulated by a wire.
export function nodeSettings(id: string): NodeSetting[] {
  const settings: NodeSetting[] = [];
  if (id === "history" || id === "wire") settings.push({ name: "Value type", value: l("Audio, Number, Gate, Integer, Array, List · по умолчанию Number", "Audio, Number, Gate, Integer, Array, List · default Number"), detail: l("Сначала выбери тип, затем подключай порты. Function и Buffer в этом списке недоступны.", "Choose the type before wiring. Function and Buffer are not available in this list.") });
  if (collectionNodes.has(id)) settings.push({ name: "Value type", value: l("Array или List · по умолчанию Array", "Array or List · default Array"), detail: l("Вход Collection принимает выбранный тип; выход коллекции использует тот же тип.", "The Collection input accepts the selected type; collection outputs use the same type.") });
  if (["array", "list", "history"].includes(id)) settings.push({ name: "Capacity", value: l("1…4096 элементов · по умолчанию 64", "1…4096 elements · default 64"), detail: l("Для History доступно при Array/List. Память выделяется до обработки; длина List не может превысить ёмкость.", "Available for Array/List History. Memory is allocated before processing; a List cannot exceed this capacity.") });
  if (["array", "list", "history"].includes(id)) settings.push({ name: "Initial values", value: id === "array" ? l("По умолчанию [1], остальные элементы — 0", "Default [1], remaining elements are 0") : l("По умолчанию пустой список", "Default empty list"), detail: l("Открой Edit initial values. Вводи конечные числа; количество не должно превышать Capacity. Для скалярной History используется числовой параметр Initial.", "Open Edit initial values. Enter finite numbers, up to Capacity. Scalar History uses the numeric Initial parameter.") });
  if (id === "curve") settings.push({ name: "Curve points", value: l("По умолчанию (−1, −1), (0, 0), (1, 1)", "Default (−1, −1), (0, 0), (1, 1)"), detail: l("Edit curve points: от 2 до 4096 пар X/Y; X строго возрастает, все значения конечны.", "Edit curve points: 2…4096 X/Y pairs; X must strictly increase and all values must be finite.") });
  if (["map", "reduce"].includes(id)) settings.push({ name: "Body", value: l("Создаётся вместе с нодой · по умолчанию Item → Result", "Created with the node · default Item → Result"), detail: l("Открой двойным щелчком или кнопкой Open node. Map: item:Number, index:Integer. Reduce также получает accumulator:Number. Единственный выход — Number.", "Double-click or choose Open node. Map receives item:Number and index:Integer. Reduce also receives accumulator:Number. The only output is Number.") });
  if (id === "subgraph") settings.push({ name: "Ports / Oversampling", value: l("До 16 входов и 16 выходов · 1× / 2× / 4×, по умолчанию 1×", "Up to 16 inputs and 16 outputs · 1× / 2× / 4×, default 1×"), detail: l("Edit ports задаёт имя, тип, единицы, диапазон, default, шкалу, ёмкость и сигнатуру. Экземпляры используют общее определение; Make independent создаёт отдельный тип.", "Edit ports defines names, types, units, ranges, defaults, scale, capacity and signature. Instances use a shared definition; Make independent creates a separate type.") });
  if (id === "interface") settings.push({ name: "Controls / Modes", value: l("До 2 ручек и 8 режимов", "Up to 2 controls and 8 modes"), detail: l("Имя, единицы, минимум, максимум, default и шкала каждой ручки задаются в Interface. Выходы Number имеют стабильные ID ручек. Оформление и режимы общие для модуля.", "Set each control’s name, unit, minimum, maximum, default and scale in Interface. Number outputs use stable control IDs. Appearance and modes belong to the module.") });
  if (id === "cpp_function") settings.push({ name: "Source / Entry function", value: l("C++23 · SDK 1", "C++23 · SDK 1"), detail: l("Выбери входную функцию и нажми Update node. Порты, диапазоны и defaults выводятся из актуального исходника; Function-выход создаётся с полной вызываемой сигнатурой.", "Choose the entry function and select Update node. Ports, ranges and defaults are derived from the current source; the Function output carries the full callable signature.") });
  if (["subgraph_input", "subgraph_output"].includes(id)) settings.push({ name: "Port definition", value: l("Настраивается через Edit ports родительской ноды", "Configured through the parent node’s Edit ports"), detail: l("Тип, default, диапазон, ёмкость и сигнатура совпадают с внешним портом по стабильному ID. Таблица портов показывает исходную Number-конфигурацию.", "Type, default, range, capacity and signature match the external port by its stable ID. The port table shows the initial Number configuration.") });
  return settings;
}
