import { l, type NodeCopy } from "./types";

const copy: Record<string, NodeCopy> = {};
function add(id: string, ru: string, en: string, exampleRu: string, exampleEn: string, related: string[], noteRu?: string, noteEn?: string) {
  copy[id] = { summary: l(ru, en), example: l(exampleRu, exampleEn), related, ...(noteRu && noteEn ? { note: l(noteRu, noteEn) } : {}) };
}

add("input", "Получает входной mono/stereo сигнал модуля от канала VLTone. Один выход может питать несколько ветвей.", "Receives the module’s mono/stereo signal from its VLTone channel. One output can feed several branches.", "В Gentle Tremolo подключи Output этой ноды к Gain / Audio и Mix / A: получатся обработанная и сухая ветви.", "In Gentle Tremolo, connect this node’s Output to Gain / Audio and Mix / A to create processed and dry branches.", ["output", "gain", "mix"], "На верхнем уровне нужен ровно один Input. Внутри собственной ноды используй Node Input.", "The top-level graph needs exactly one Input. Use Node Input inside a custom node.");
add("output", "Возвращает результат обработки в канал. Сюда должен прийти конечный аудиосигнал.", "Returns the processed signal to the channel. Connect your final audio signal here.", "Соедини Mix / Output → Output / Audio. Ноды, не ведущие к выходу, остаются в редакторе, но не исполняются.", "Connect Mix / Output → Output / Audio. Nodes that do not contribute to an output stay in the editor but are not executed.", ["input", "mix"], "Выходной Audio-вход обязателен. На верхнем уровне должен быть один Output.", "The Audio input is required. The top-level graph must contain one Output.");
add("interface", "Задаёт имя, внешний вид карточки мини-модуля и до двух внешних ручек. Выход каждой ручки — поток Number.", "Defines the mini-module name, card appearance and up to two external controls. Each control outputs a Number stream.", "Создай Rate (0.1–10 Hz, default 1.8) и Depth (0–1, default 0.35). Подключи Rate к LFO / Rate, Depth к Mix / Mix.", "Create Rate (0.1–10 Hz, default 1.8) and Depth (0–1, default 0.35). Connect Rate to LFO / Rate and Depth to Mix / Mix.", ["lfo", "mix", "gain"], "Порты создаются из ручек проекта; их ID сохраняют адреса автоматизации. Переименовывай ручку вместо удаления и повторного создания.", "Ports come from the project’s controls; their stable IDs preserve automation addresses. Rename controls instead of deleting and recreating them.");
add("constant", "Выдаёт числовое значение. Подключённый вход Value заменяет ручное значение.", "Outputs a number. A connected Value input replaces the stored manual value.", "Установи Value = 0.5 и подключи выход к Gain / Gain для половинной амплитуды.", "Set Value to 0.5 and connect it to Gain / Gain for half amplitude.", ["gain", "add"]);
add("gain", "Умножает оба аудиоканала на Gain. Коэффициент плавно следует цели с постоянной времени 10 ms.", "Multiplies both audio channels by Gain. The coefficient follows its target with a 10 ms time constant.", "Input → Gain → Mix / B; LFO с Amount 0.5 и Offset 0.5 → Gain / Gain создаёт тремоло.", "Input → Gain → Mix / B; an LFO with Amount 0.5 and Offset 0.5 → Gain / Gain creates tremolo.", ["lfo", "mix", "audio_scale"], "Gain — линейный коэффициент 0–2, не dB. Для знакопеременного усиления используй Scale Audio.", "Gain is a linear factor from 0 to 2, not dB. Use Scale Audio for negative gain.");
add("mix", "Линейно смешивает A и B: A × (1 − Mix) + B × Mix. Коэффициент сглаживается за 10 ms.", "Linearly blends A and B: A × (1 − Mix) + B × Mix. The coefficient uses 10 ms smoothing.", "Сухой Input → A, обработанный Gain → B, ручка Depth → Mix. При Depth = 0 слышна сухая ветвь.", "Dry Input → A, processed Gain → B, Depth control → Mix. Depth = 0 gives the dry branch.", ["input", "gain", "interface"], "Подключи оба Audio-входа. Это линейный, а не equal-power кроссфейд.", "Connect both Audio inputs. This is a linear, not equal-power, crossfade.");

const binary = [
  ["add", "Складывает A и B", "Adds A and B", "2 + 3 = 5"],
  ["subtract", "Вычитает B из A", "Subtracts B from A", "5 − 3 = 2"],
  ["multiply", "Умножает A на B", "Multiplies A by B", "0.5 × 2 = 1"],
  ["divide", "Делит A на B; при |B| < 1e−20 возвращает 0", "Divides A by B; returns 0 when |B| < 1e−20", "6 / 3 = 2"],
  ["min", "Выбирает меньшее из A и B", "Selects the smaller of A and B", "min(2, 5) = 2"],
  ["max", "Выбирает большее из A и B", "Selects the larger of A and B", "max(2, 5) = 5"],
  ["power", "Возводит A в степень B", "Raises A to the power B", "2³ = 8"],
  ["modulo", "Возвращает остаток fmod(A, B); при B = 0 результат 0", "Returns fmod(A, B); a zero divisor gives 0", "fmod(5, 3) = 2"],
];
for (const [id, ru, en, expression] of binary) add(id, ru + " на каждом сэмпле.", en + " on every sample.", `Пример: ${expression}. Подключи Number к A; B можно задать вручную или другим проводом.`, `Example: ${expression}. Connect a Number to A; set B manually or connect another Number.`, ["constant", "clamp", "map_range"], "Эти входы принимают Number. Для аудио используй ноды Signal или явное преобразование. Не допускай NaN/Infinity в формуле.", "These inputs accept Number. Use Signal nodes or an explicit conversion for audio. Keep the formula finite.");
const unary = [
  ["abs", "Модуль числа", "Absolute value", "abs(−0.5) = 0.5"],
  ["negate", "Меняет знак числа", "Negates a number", "−(0.5) = −0.5"],
  ["sqrt", "Квадратный корень; отрицательный вход даёт 0", "Square root; negative input gives 0", "sqrt(0.25) = 0.5"],
  ["sin", "Синус угла в радианах", "Sine of an angle in radians", "sin(π / 2) = 1"],
  ["cos", "Косинус угла в радианах", "Cosine of an angle in radians", "cos(0) = 1"],
  ["exp", "Экспонента eˣ; аргумент ограничен от −80 до ln(10⁶)", "Exponential eˣ; input is limited to −80…ln(10⁶)", "exp(0) = 1"],
  ["log", "Натуральный логарифм; аргумент не меньше 1e−20", "Natural logarithm with an input floor of 1e−20", "ln(1) = 0"],
  ["log2", "Логарифм по основанию 2; аргумент не меньше 1e−20", "Base-2 logarithm with an input floor of 1e−20", "log₂(8) = 3"],
  ["log10", "Десятичный логарифм; аргумент не меньше 1e−20", "Base-10 logarithm with an input floor of 1e−20", "log₁₀(100) = 2"],
  ["tanh", "Гиперболический тангенс, мягко ограничивающий выход между −1 и 1", "Hyperbolic tangent, softly bounding the output between −1 and 1", "tanh(0) = 0"],
  ["atan", "Арктангенс; результат в радианах", "Arctangent; output is in radians", "atan(1) = π / 4"],
  ["sign", "Возвращает −1, 0 или 1 в зависимости от знака", "Returns −1, 0 or 1 according to the sign", "sign(−2) = −1"],
  ["floor", "Округляет вниз", "Rounds downward", "floor(−1.2) = −2"],
  ["ceil", "Округляет вверх", "Rounds upward", "ceil(1.2) = 2"],
  ["round", "Округляет к ближайшему целому; половины от нуля", "Rounds to the nearest integer, with ties away from zero", "round(−1.5) = −2"],
  ["fraction", "Вычитает floor(x), оставляя дробную часть от 0 до 1", "Subtracts floor(x), giving a fractional part from 0 to 1", "fraction(−0.2) = 0.8"],
  ["linear_to_db", "Преобразует амплитуду в dB: 20 × log₁₀(max(1e−9, |x|))", "Converts amplitude to dB: 20 × log₁₀(max(1e−9, |x|))", "1 → 0 dB; 0 → −180 dB"],
  ["db_to_linear", "Преобразует dB в амплитуду: 10^(x/20); x ограничен −180…120 dB", "Converts dB to amplitude: 10^(x/20), with x limited to −180…120 dB", "0 dB → 1; −20 dB → 0.1"],
];
for (const [id, ru, en, expression] of unary) add(id, ru + ". Вычисляется для каждого сэмпла Number.", en + ". Evaluated for each Number sample.", `Пример: ${expression}. Constant / Output → Value; результат можно направить в параметр другой ноды.`, `Example: ${expression}. Constant / Output → Value; route the result to another node’s parameter.`, ["constant", "map_range", "number_to_integer"]);
add("clamp", "Ограничивает Value интервалом между Minimum и Maximum; порядок границ не важен.", "Clamps Value between Minimum and Maximum; the bounds may be reversed.", "LFO → Value, Minimum = 0, Maximum = 1 → Mix / Mix.", "LFO → Value, Minimum = 0, Maximum = 1 → Mix / Mix.", ["lfo", "mix", "map_range"]);
add("map_range", "Линейно переводит Value из входного диапазона в выходной, включая значения за границами.", "Linearly maps Value from an input range to an output range, including values outside the bounds.", "Переведи LFO −1…1 в 200…4000 Hz и направь результат в EQ Band / Frequency.", "Map an LFO from −1…1 to 200…4000 Hz and connect it to EQ Band / Frequency.", ["lfo", "eq_band", "clamp"], "Диапазон не обрезается автоматически. При одинаковых входных границах результат равен Output min.", "The output is not automatically clamped. Equal input bounds return Output min.");
add("lerp", "Интерполирует A + (B − A) × Position. Position вне 0…1 даёт экстраполяцию.", "Interpolates A + (B − A) × Position. Position outside 0…1 extrapolates.", "A = 200, B = 1000, Position = 0.5 → 600. Подключи ручку Interface к Position.", "A = 200, B = 1000, Position = 0.5 → 600. Connect an Interface control to Position.", ["interface", "map_range", "clamp"]);
for (const [id, ru, en, ex] of [["wrap", "Циклически возвращает число в диапазон", "Wraps a value back into the range", "0…1: 1.2 → 0.2"], ["fold", "Отражает число от границ диапазона", "Reflects a value at the range boundaries", "0…1: 1.2 → 0.8"], ["smoothstep", "Плавно переводит нормализованный вход от 0 к 1 по кривой t²(3−2t)", "Smoothly maps the normalized input from 0 to 1 using t²(3−2t)", "0…1: 0.5 → 0.5"]]) add(id, ru + ".", en + ".", `Пример: ${ex}. Подай модуляцию в Value и задай Minimum/Maximum.`, `Example: ${ex}. Feed modulation into Value and set Minimum/Maximum.`, ["lfo", "clamp", "map_range"]);
add("compare", "Сравнивает A и B выбранной операцией >, <, =, >= или <=. Результат — Gate.", "Compares A and B using >, <, =, >= or <=. Outputs a Gate.", "Envelope Follower → A, B = 0.1, Operation = >; направь Gate в Select Audio.", "Envelope Follower → A, B = 0.1, Operation = >; feed the Gate into Select Audio.", ["envelope", "audio_select", "rising_edge"]);
for (const [id, kind, a, b] of [["select", "Number", "constant", "constant"], ["audio_select", "Audio", "input", "gain"]]) add(id, `Выбирает вход A, когда Gate выключен, и B, когда включён. Оба входа имеют тип ${kind}.`, `Selects A while Gate is off and B while it is on. Both inputs are ${kind}.`, `Compare → Select B; ${a} → A, ${b} → B.`, `Compare → Select B; ${a} → A, ${b} → B.`, ["compare", a, "mix"], "Переключение мгновенное. Для плавного перехода аудио используй Mix.", "Switching is immediate. Use Mix for a smooth audio transition.");
for (const [id, ru, en, ex] of [["and", "Включается, когда оба Gate включены", "True when both Gates are on", "1 AND 1 = 1"], ["or", "Включается, когда хотя бы один Gate включён", "True when at least one Gate is on", "0 OR 1 = 1"], ["xor", "Включается, когда состояния Gate различаются", "True when the Gate states differ", "1 XOR 1 = 0"], ["not", "Инвертирует состояние Gate: выключенный вход включает выход, и наоборот", "Inverts a Gate: an off input turns the output on, and vice versa", "NOT 0 = 1"]]) add(id, ru + ".", en + ".", `${ex}. Подключи выходы Compare к входам Gate.`, `${ex}. Connect Compare outputs to the Gate inputs.`, ["compare", "gate_to_number", "select"]);
for (const [id, ru, en] of [["rising_edge", "из выключенного во включённое", "from off to on"], ["falling_edge", "из включённого в выключенное", "from on to off"]]) add(id, `Выдаёт Gate длиной один сэмпл при переходе ${ru}.`, `Outputs a one-sample Gate when the input changes ${en}.`, "Compare → Gate; выход → Counter / Trigger для подсчёта переходов.", "Compare → Gate; output → Counter / Trigger to count transitions.", ["compare", "counter", "sample_hold"]);
add("gate_to_number", "Преобразует Gate в Number: выключено = 0, включено = 1.", "Converts Gate to Number: off = 0, on = 1.", "Compare → Gate to Number → Smooth → Gain / Gain для управляемого открытия громкости.", "Compare → Gate to Number → Smooth → Gain / Gain for a smoothed volume gate.", ["compare", "smooth", "gain"]);
add("number_to_gate", "Преобразует Number в Gate: любое ненулевое значение включает выход.", "Converts Number to Gate: any nonzero value turns the output on.", "Constant = 0 → выключено; Constant = −1 → включено. Для порога используй Compare.", "Constant = 0 → off; Constant = −1 → on. Use Compare for a threshold.", ["constant", "compare", "gate_to_number"]);
add("number_to_integer", "Обрезает дробную часть к нулю и ограничивает результат диапазоном 32-битного знакового целого.", "Truncates toward zero and clamps to the signed 32-bit integer range.", "Constant = 2.9 → Number to Integer → Get Element / Index выбирает элемент 2.", "Constant = 2.9 → Number to Integer → Get Element / Index selects element 2.", ["get", "integer_to_number", "round"]);
add("integer_to_number", "Преобразует Integer в Number для подключения к числовым параметрам.", "Converts Integer to Number for numeric parameter inputs.", "Counter → Integer to Number → Divide / A, B = 8: получи число циклов из количества импульсов.", "Counter → Integer to Number → Divide / A, B = 8: turn pulse counts into cycle counts.", ["counter", "divide", "number_to_integer"]);

add("smooth", "Однополюсное сглаживание Number с задаваемой постоянной времени.", "One-pole smoothing of a Number with an adjustable time constant.", "Interface → Value, Time = 20 ms; выход → параметр эффекта для смягчения скачков.", "Interface → Value, Time = 20 ms; output → an effect parameter to soften jumps.", ["interface", "attack_release", "slew"]);
add("attack_release", "Сглаживает растущее значение с Attack, падающее — с Release.", "Smooths rising values with Attack and falling values with Release.", "Peak Detector → Value; Attack = 10 ms, Release = 100 ms для огибающей громкости.", "Peak Detector → Value; Attack = 10 ms, Release = 100 ms for a level envelope.", ["peak", "envelope", "smooth"]);
add("slew", "Ограничивает скорость роста и падения Number в единицах в секунду.", "Limits the rise and fall speed of a Number in units per second.", "Gate to Number → Value; Rise = 2 означает подъём от 0 до 1 за 0.5 s.", "Gate to Number → Value; Rise = 2 takes 0.5 s to move from 0 to 1.", ["gate_to_number", "smooth", "attack_release"]);
add("sample_hold", "На фронте Trigger запоминает Value и удерживает его до следующего фронта.", "Captures Value on a rising Trigger edge and holds it until the next edge.", "Random → Value, Compare от другого LFO → Trigger: получи ступенчатую модуляцию.", "Random → Value, Compare driven by another LFO → Trigger: create stepped modulation.", ["random", "compare", "lfo"], "Постоянно включённый Gate не пересэмплирует значение. Нужен новый переход из 0 в 1.", "A continuously high Gate does not resample the value. A new off-to-on transition is required.");
add("lfo", "Генерирует Number-модуляцию: Sine, Triangle, Saw или Square. Частота задаётся в Hz либо синхронизируется с темпом.", "Generates Number modulation: Sine, Triangle, Saw or Square. Rate is in Hz or synchronized to tempo.", "Для Gentle Tremolo: Rate = 1.8 Hz, Amount = 0.5, Offset = 0.5. Выход 0…1 → Gain / Gain.", "For Gentle Tremolo: Rate = 1.8 Hz, Amount = 0.5, Offset = 0.5. Connect the 0…1 output to Gain / Gain.", ["gain", "map_range", "interface"], "Amount — амплитуда, Offset — смещение. Reset перезапускает фазу по фронту Gate. Shape, Clock и Cycle length задаются статически.", "Amount is amplitude; Offset is the DC offset. A rising Reset Gate restarts phase. Shape, Clock and Cycle length are static settings.");
add("random", "Создаёт детерминированную случайную модуляцию от −1 до 1 с частотой обновления Rate.", "Creates deterministic random modulation from −1 to 1 at the Rate update frequency.", "Random → Map Range (−1…1 → 300…3000) → EQ Band / Frequency. Smooth смягчает переходы.", "Random → Map Range (−1…1 → 300…3000) → EQ Band / Frequency. Smooth softens the transitions.", ["map_range", "eq_band", "sample_hold"], "Seed фиксирует локальную последовательность; Reset начинает её заново. Это управляющий Number, не аудиошум.", "Seed fixes the local sequence; Reset starts it again. This is a Number control source, not audio noise.");
add("envelope", "Извлекает огибающую Audio через Peak или RMS-детектор и сглаживает её временами Attack/Release.", "Extracts an Audio envelope with a Peak or RMS detector and Attack/Release smoothing.", "Input → Envelope Follower → Map Range → EQ Band / Frequency для фильтра, реагирующего на громкость.", "Input → Envelope Follower → Map Range → EQ Band / Frequency for a level-responsive filter.", ["peak", "window_rms", "map_range"]);
add("peak", "На каждом сэмпле выдаёт максимальный модуль левого и правого каналов без сглаживания.", "Outputs the larger absolute left/right sample value without smoothing.", "Input → Peak Detector → Attack / Release, чтобы отдельно настроить огибающую.", "Input → Peak Detector → Attack / Release to shape an envelope explicitly.", ["attack_release", "envelope", "window_rms"]);
add("window_rms", "Считает корень из среднего квадрата двух каналов в скользящем окне.", "Calculates the root mean square of both channels over a sliding window.", "Input → Window RMS с Window = 10 ms → Compare для детектора уровня.", "Input → Window RMS with Window = 10 ms → Compare for a level detector.", ["compare", "envelope", "peak"], "Window — структурный параметр: размер памяти подготавливается перед обработкой, этот параметр не модулируется.", "Window is structural: storage is prepared before processing, so it cannot be modulated.");
add("audio_to_number", "Извлекает из Audio отдельный сэмпл Left, Right или среднее (Left + Right) / 2.", "Extracts Left, Right or the average (Left + Right) / 2 from an Audio sample.", "Input → Audio to Number → Tanh → Number to Audio создаёт монофоническое преобразование сигнала.", "Input → Audio to Number → Tanh → Number to Audio creates a mono waveshaping path.", ["number_to_audio", "stereo_split", "envelope"], "Это мгновенный сэмпл, а не измеритель громкости. Для уровня используй Envelope Follower.", "This is an instantaneous sample, not a level measurement. Use Envelope Follower for level.");
add("number_to_audio", "Копирует Number в оба канала Audio.", "Copies a Number into both Audio channels.", "Sine → Value → Output превращает вычисленный сигнал в mono/stereo аудиовыход.", "Sine → Value → Output turns a computed signal into a mono/stereo audio output.", ["audio_to_number", "stereo_join", "oscillator"], "Постоянный Number создаёт DC. Для удаления постоянной составляющей подключи DC Block.", "A constant Number produces DC. Use DC Block to remove the offset.");
add("oscillator", "Генерирует Audio с формами Sine, Triangle, Saw и Square. Несинусоидальные формы используют коррекцию фронтов.", "Generates Audio with Sine, Triangle, Saw and Square shapes. Non-sine shapes use edge corrections.", "Oscillator (440 Hz, Level 0.1) → Output для тестового тона. Reset получает Gate.", "Oscillator (440 Hz, Level 0.1) → Output for a test tone. Reset accepts Gate.", ["noise", "lfo", "output"], "Не требует Input-подключения. Это генератор сигнала; MIDI и полифония не являются его входами.", "No Audio input is required. This is a signal generator; it does not expose MIDI or polyphonic inputs.");
add("noise", "Генерирует белый Audio-шум с детерминированным состоянием. В stereo каналы получают разные значения.", "Generates white Audio noise with deterministic state. Stereo channels receive different values.", "White Noise (Level 0.05) → EQ Band → Output для прослушивания фильтра.", "White Noise (Level 0.05) → EQ Band → Output to audition a filter.", ["eq_band", "oscillator", "random"]);

for (const [id, ru, en, example] of [
  ["color", "Окрашивает аудиосигнал встроенным процессором Color", "Colors audio with the built-in Color processor", "Input → Color → Output"],
  ["doubler", "Создаёт ощущение удвоенного исполнения короткими вариациями сигнала", "Creates a doubled-performance feel with short signal variations", "Input → Doubler → Mix / B"],
  ["chorus", "Добавляет модулируемые копии сигнала для хорового звучания", "Adds modulated copies for a chorus sound", "Input → Chorus → Output"],
  ["flanger", "Смешивает сигнал с короткой модулируемой задержкой для гребенчатого эффекта", "Combines audio with a short modulated delay for a comb-filter effect", "Input → Flanger → Output"],
  ["phaser", "Изменяет фазовые соотношения для движущихся провалов в спектре", "Changes phase relationships to create moving spectral notches", "Input → Phaser → Output"],
  ["delay", "Добавляет задержанные повторы с настройками штатного Delay", "Adds delayed repeats using the built-in Delay controls", "Input → Delay → Output"],
  ["compressor", "Уменьшает динамический диапазон с настройками штатного Compressor", "Reduces dynamic range with the built-in Compressor controls", "Input → Compressor → Output"],
  ["eq_band", "Обрабатывает сигнал одной полосой эквалайзера с выбранным типом фильтра", "Processes audio with one equalizer band and a selected filter type", "Input → EQ Band → Output"],
  ["reverb", "Создаёт реверберацию сетью comb/allpass-фильтров с настройками Room/Hall", "Creates reverb with a comb/allpass network and Room/Hall settings", "Input → Reverb → Output"],
]) add(id, ru + ". Параметры ниже соответствуют нативному реестру.", en + ". The parameters below come from the native registry.", `${example}. Подключи Interface или LFO к доступному входу Number, чтобы управлять параметром.`, `${example}. Connect Interface or an LFO to an available Number input to control a parameter.`, ["input", "interface", "mix", "lfo"], "Модулируются только параметры с соответствующим входом. Переключатели и структурные настройки остаются ручными.", "Only parameters with matching inputs can be modulated. Switches and structural settings remain manual.");
for (const [id, ru, en, ex] of [["audio_add", "Складывает Audio A и B поканально", "Adds Audio A and B channel by channel", "A + B"], ["audio_subtract", "Вычитает Audio B из A поканально", "Subtracts Audio B from A channel by channel", "A − B"], ["audio_multiply", "Умножает Audio A и B поканально", "Multiplies Audio A and B channel by channel", "A × B"]]) add(id, ru + ".", en + ".", `Формула: ${ex}. Подключи Input к A и Oscillator к B; результат → Output.`, `Formula: ${ex}. Connect Input to A and Oscillator to B; result → Output.`, ["input", "oscillator", "audio_scale"], "Оба аудиовхода обязательны. При суммировании учитывай рост амплитуды.", "Both Audio inputs are required. Summing can increase the amplitude.");
add("audio_scale", "Умножает Audio на Number без встроенного сглаживания; допускает отрицательный коэффициент.", "Multiplies Audio by a Number without built-in smoothing; negative factors are allowed.", "Input → Audio; Gain = −1 инвертирует полярность обоих каналов.", "Input → Audio; Gain = −1 inverts the polarity of both channels.", ["gain", "smooth", "audio_multiply"]);
add("stereo_split", "Разделяет Audio на потоки Number Left и Right.", "Splits Audio into Left and Right Number streams.", "Input → Split Stereo; каждый канал → Tanh; результаты → Join Stereo.", "Input → Split Stereo; each channel → Tanh; results → Join Stereo.", ["stereo_join", "tanh", "audio_to_number"]);
add("stereo_join", "Собирает Audio из двух потоков Number Left и Right.", "Builds Audio from Left and Right Number streams.", "Split Stereo / Left → Left, Split Stereo / Right → Right; Output → Output / Audio.", "Split Stereo / Left → Left, Split Stereo / Right → Right; Output → Output / Audio.", ["stereo_split", "number_to_audio"]);
add("ms_encode", "Кодирует stereo в Number Mid = (L + R) / 2 и Side = (L − R) / 2.", "Encodes stereo into Number Mid = (L + R) / 2 and Side = (L − R) / 2.", "Input → Encode Mid-Side; умножь Side на 0.5 и подключи оба сигнала к Decode Mid-Side.", "Input → Encode Mid-Side; multiply Side by 0.5 and connect both signals to Decode Mid-Side.", ["ms_decode", "multiply", "stereo_split"]);
add("ms_decode", "Восстанавливает stereo: L = Mid + Side, R = Mid − Side.", "Reconstructs stereo: L = Mid + Side, R = Mid − Side.", "Encode Mid-Side / Mid → Mid, Side → Side; Output → Output / Audio.", "Encode Mid-Side / Mid → Mid, Side → Side; Output → Output / Audio.", ["ms_encode", "stereo_join"]);

add("wire", "Передаёт именованное значение без изменения. Тип, имя и сигнатура определяются настройками ноды.", "Passes a named value unchanged. Its type, name and signature come from the node settings.", "Назови ноду Cutoff и передай через неё Number от Interface к нескольким фильтрам.", "Name the node Cutoff and pass an Interface Number through it to several filters.", ["interface", "subgraph_input", "subgraph_output"], "Это не задержка. Named Value не разрывает цикл обратной связи.", "This is not a delay. Named Value does not break a feedback cycle.");
add("history", "Хранит значение предыдущего сэмпла. Сначала отдаёт старое состояние, затем записывает Next.", "Stores the previous sample’s value. It outputs the old state before committing Next.", "History → Add / A; B = 0.01; Add → History / Next. Такая обратная связь содержит явную память.", "History → Add / A; B = 0.01; Add → History / Next. This feedback path contains explicit memory.", ["add", "accumulator", "delay_buffer"], "Write enable по умолчанию включён; Reset имеет приоритет. Настрой тип значения до соединения. Function и Buffer нельзя хранить в History.", "Write enable defaults to on; Reset takes priority. Choose the value type before wiring. History cannot store Function or Buffer.");
add("accumulator", "На каждом сэмпле прибавляет Increment к состоянию. При включённом Reset выдаёт 0.", "Adds Increment to its state every sample. Outputs 0 while Reset is on.", "Increment = 1 / Sample Rate из Time / Context создаёт счётчик времени в секундах.", "Increment = 1 / Sample Rate from Time / Context creates a time counter in seconds.", ["context", "divide", "counter"], "Это посэмпловый накопитель, не счётчик импульсов. Для фронтов Gate используй Counter.", "This is a per-sample accumulator, not a pulse counter. Use Counter for Gate edges.");
add("counter", "Увеличивает Integer на единицу по переднему фронту Trigger. Reset обнуляет счётчик.", "Increments an Integer on each rising Trigger edge. Reset clears the count.", "LFO → Compare (> 0) → Trigger. Counter → Integer to Number → параметр схемы.", "LFO → Compare (> 0) → Trigger. Counter → Integer to Number → a graph parameter.", ["compare", "integer_to_number", "accumulator"], "При переполнении 2147483647 счётчик переходит к −2147483648.", "The counter wraps from 2147483647 to −2147483648 on overflow.");
add("context", "Предоставляет Sample Rate, Time, Tempo, Beat и Gate Playing из контекста обработки.", "Exposes Sample Rate, Time, Tempo, Beat and the Playing Gate from the processing context.", "Tempo → Divide / A, B = 60: получи частоту четвертей в Hz. Playing можно использовать в логике.", "Tempo → Divide / A, B = 60 gives quarter-note frequency in Hz. Use Playing in logic.", ["divide", "lfo", "accumulator"]);
add("delay_buffer", "Записывает Audio в подготовленный кольцевой буфер и отдаёт ссылку Buffer для чтения.", "Writes Audio into a prepared ring buffer and exposes a Buffer reference for reading.", "Input → Audio; Buffer → Read Delay Tap / Buffer. Несколько Read Delay Tap могут читать один буфер.", "Input → Audio; Buffer → Read Delay Tap / Buffer. Multiple taps can read the same buffer.", ["delay_read", "audio_add", "history"], "Maximum delay задаёт объём памяти до обработки. Reset очищает историю по переднему фронту.", "Maximum delay determines storage before processing. A rising Reset clears the history.");
add("delay_read", "Читает задержанный Audio из Buffer с линейной интерполяцией между сэмплами.", "Reads delayed Audio from a Buffer, interpolating linearly between samples.", "Delay Buffer → Buffer; Delay = 100 ms; Output → Mix / B. Ручка Interface может менять Delay.", "Delay Buffer → Buffer; Delay = 100 ms; Output → Mix / B. An Interface control can change Delay.", ["delay_buffer", "mix", "interface"], "Минимальное фактическое чтение — один сэмпл, даже при 0 ms. Время ограничивается ёмкостью подключённого буфера.", "The minimum actual read delay is one sample, even at 0 ms. Delay is capped by the connected buffer’s capacity.");
add("one_pole", "Однополюсный фильтр: y = (1 − Pole) × x + Pole × y_previous.", "One-pole filter: y = (1 − Pole) × x + Pole × y_previous.", "Input → One Pole (Pole = 0.9) → Output сглаживает высокочастотные изменения.", "Input → One Pole (Pole = 0.9) → Output smooths high-frequency changes.", ["biquad", "dc_block", "smooth"]);
add("biquad", "Фильтр второго порядка с массивом нормализованных коэффициентов b0, b1, b2, a1, a2.", "Second-order filter taking normalized coefficients b0, b1, b2, a1, a2.", "Input → Audio; Biquad Coefficients → коэффициенты; Output → Output / Audio.", "Input → Audio; Biquad Coefficients → coefficients; Output → Output / Audio.", ["biquad_coefficients", "array", "fir"], "Нужен массив ровно из пяти коэффициентов. Произвольные нестабильные коэффициенты могут дать некорректный DSP.", "Exactly five coefficients are required. Arbitrary unstable coefficients can produce invalid DSP.");
add("biquad_coefficients", "Рассчитывает пять коэффициентов выбранного фильтра по Frequency, Q, Gain и частоте дискретизации.", "Calculates five coefficients for the selected filter from Frequency, Q, Gain and sample rate.", "Выбери Low Pass, Frequency = 1000 Hz, Q = 0.707; Array-выход → Biquad / coefficients.", "Choose Low Pass, Frequency = 1000 Hz, Q = 0.707; Array output → Biquad / coefficients.", ["biquad", "interface", "lfo"], "Frequency ограничивается внутри расчёта до 0.49 × Sample Rate. Тип фильтра статический.", "Frequency is internally limited to 0.49 × Sample Rate. Filter type is static.");
add("fir", "Выполняет конечную импульсную свёртку Audio с коэффициентами Array.", "Convolves Audio with a finite Array of FIR coefficients.", "Array с коэффициентами 0.5, 0.5 → Coefficients; Input → Audio: усреднение соседних сэмплов.", "An Array containing 0.5, 0.5 → Coefficients; Input → Audio averages adjacent samples.", ["array", "biquad", "delay_buffer"], "Массив должен быть непустым и помещаться в подготовленную ёмкость.", "The coefficient array must be nonempty and fit the prepared capacity.");
add("dc_block", "Удаляет постоянную составляющую Audio однополюсным фильтром высоких частот.", "Removes DC from Audio with a one-pole high-pass filter.", "После Hard Clip или собственного waveshaper подключи DC Block с Cutoff = 10 Hz.", "Place DC Block with Cutoff = 10 Hz after Hard Clip or a custom waveshaper.", ["hard_clip", "curve", "one_pole"]);
add("hard_clip", "Жёстко ограничивает каждый аудиоканал диапазоном −Limit…+Limit.", "Hard-clips each audio channel to −Limit…+Limit.", "Input → Scale Audio (Gain 2) → Hard Clip (Limit 0.8) → Output.", "Input → Scale Audio (Gain 2) → Hard Clip (Limit 0.8) → Output.", ["audio_scale", "dc_block", "subgraph"], "Нелинейность создаёт гармоники. Собственная нода с oversampling помогает уменьшить алиасинг.", "The nonlinearity creates harmonics. An oversampled custom node helps reduce aliasing.");
add("curve", "Линейно интерполирует Number по упорядоченным точкам передаточной кривой.", "Linearly interpolates a Number using ordered transfer-curve points.", "Задай точки (−1, −0.5), (0, 0), (1, 0.5): Value = 0.5 даст 0.25.", "Set points (−1, −0.5), (0, 0), (1, 0.5): Value = 0.5 gives 0.25.", ["table_lookup", "audio_to_number", "tanh"], "Точки задаются парами x,y с возрастающими x. За пределами кривой удерживаются крайние значения.", "Enter x,y pairs with increasing x. Values outside the curve hold the endpoint values.");
add("table_lookup", "Читает Array по нормализованной позиции 0…1 с линейной интерполяцией.", "Reads an Array at a normalized position from 0 to 1, with linear interpolation.", "Array = [0, 0.5, 1], Position = 0.25 → 0.25. Подключи модуляцию к Position.", "Array = [0, 0.5, 1], Position = 0.25 → 0.25. Connect modulation to Position.", ["array", "curve", "get"], "Position — нормализованная координата. Для целочисленного индекса используй Get Element.", "Position is normalized. Use Get Element for an integer index.");

add("array", "Создаёт коллекцию Number фиксированной ёмкости. Незаданные элементы заполнены нулями.", "Creates a fixed-capacity Number collection. Unspecified elements are zero-filled.", "Задай Capacity = 2, Values = 0.5, 0.5 и подключи выход к FIR / Coefficients.", "Set Capacity = 2, Values = 0.5, 0.5 and connect the output to FIR / Coefficients.", ["fir", "list", "get"], "Ёмкость от 1 до 4096 задаётся до обработки. Values — настройки ноды, а не входные провода.", "Capacity, from 1 to 4096, is set before processing. Values are node settings, not input wires.");
add("list", "Создаёт коллекцию Number с переменной длиной внутри заранее выделенной ёмкости.", "Creates a variable-length Number collection within a preallocated capacity.", "List с Capacity = 8 и Values = 1, 2 → Append / Collection; Value = 3 даёт [1, 2, 3].", "List with Capacity = 8 and Values = 1, 2 → Append / Collection; Value = 3 gives [1, 2, 3].", ["append", "remove", "history"], "Append не увеличивает выделенную ёмкость. Для накопления результата между сэмплами нужна History.", "Append does not grow allocated capacity. Use History to retain changes between samples.");
add("length", "Возвращает длину Array или List как Integer.", "Returns an Array or List length as an Integer.", "List с Values = 2, 4, 6 → Length → Integer to Number даёт 3.", "A List containing 2, 4, 6 → Length → Integer to Number gives 3.", ["list", "array", "integer_to_number"]);
add("get", "Читает элемент по Integer-индексу. Возвращает Number и Gate Valid.", "Reads an element at an Integer index. Outputs a Number and a Valid Gate.", "Array = [10, 20, 30]; Index = 1 через Number to Integer → результат 20, Valid включён.", "Array = [10, 20, 30]; Index = 1 through Number to Integer → 20 with Valid on.", ["array", "number_to_integer", "set"], "Индексация начинается с 0. Неверный индекс даёт 0 и выключенный Valid.", "Indices start at 0. An invalid index gives 0 and Valid off.");
for (const [id, ru, en, er, ee] of [
  ["set", "Возвращает копию коллекции с заменённым элементом", "Returns a copy of a collection with one element replaced", "[1, 2], Index = 0, Value = 9 → [9, 2]", "[1, 2], Index = 0, Value = 9 → [9, 2]"],
  ["append", "Возвращает List с добавленным в конец элементом", "Returns a List with a value appended", "[1, 2], Value = 3 → [1, 2, 3]", "[1, 2], Value = 3 → [1, 2, 3]"],
  ["remove", "Возвращает List без элемента с выбранным индексом", "Returns a List without the indexed element", "[1, 2, 3], Index = 1 → [1, 3]", "[1, 2, 3], Index = 1 → [1, 3]"],
  ["clear", "Обнуляет элементы Array либо возвращает пустой List", "Zeroes an Array or returns an empty List", "Array [1, 2] → [0, 0]; List [1, 2] → []", "Array [1, 2] → [0, 0]; List [1, 2] → []"],
]) add(id, ru + ". Gate Success показывает успех операции.", en + ". The Success Gate reports whether the operation succeeded.", er + ". Подключи коллекцию к Collection.", ee + ". Connect the collection to Collection.", [id === "append" || id === "remove" ? "list" : "array", "history", "get"], "Исходная коллекция не изменяется. Неверный индекс или переполненная ёмкость выключают Success; для сохранения изменений используй History.", "The source collection is unchanged. An invalid index or exhausted capacity turns Success off; use History to retain changes.");
for (const [id, ru, en, ex] of [["sum", "Суммирует элементы коллекции", "Sums collection elements", "[1, 2, 3] → 6"], ["collection_min", "Находит минимальный элемент коллекции", "Finds the minimum collection element", "[1, 2, 3] → 1"], ["collection_max", "Находит максимальный элемент коллекции", "Finds the maximum collection element", "[1, 2, 3] → 3"]]) add(id, ru + ". Результат — Number.", en + ". Outputs a Number.", `${ex}. Array или List → Collection.`, `${ex}. Array or List → Collection.`, ["array", "list", "reduce"], "Пустая коллекция возвращает 0.", "An empty collection returns 0.");
add("map", "Применяет пользовательский подграф к каждому элементу Array или List и собирает выходную коллекцию.", "Applies a custom subgraph to every Array or List element and collects the results.", "Создай подграф с входами item:Number, index:Integer и одним Number-выходом, умножающий item на 2; Map преобразует [1, 2] в [2, 4].", "Create a subgraph with item:Number and index:Integer inputs and one Number output that doubles item; Map turns [1, 2] into [2, 4].", ["subgraph", "array", "multiply", "reduce"], "Тело создаётся вместе с Map: открой его двойным щелчком или кнопкой Open node. Тип коллекции задаётся настройкой Array/List; Function-провод C++ сюда не подключается.", "Map creates its body automatically: double-click or choose Open node to edit it. Choose Array/List in the node settings; a C++ Function wire is not used here.");
add("reduce", "Последовательно сворачивает коллекцию пользовательским подграфом, начиная со значения Initial.", "Folds a collection through a custom subgraph, starting from Initial.", "Подграф с входами accumulator:Number, item:Number, index:Integer и суммой accumulator + item на Number-выходе; Initial = 0, [1, 2, 3] → 6.", "Use a subgraph with accumulator:Number, item:Number and index:Integer inputs, and accumulator + item as its Number output; Initial = 0, [1, 2, 3] → 6.", ["subgraph", "add", "sum", "map"], "Входы определяются ID item, index и accumulator. Тело поддерживает только элементарные ноды; выход — Number.", "Inputs are identified by item, index and accumulator IDs. The body supports elementary nodes only; its output must be Number.");
add("subgraph", "Объединяет обработку в собственную ноду с именованными портами. Экземпляры разделяют определение, но имеют независимое DSP-состояние.", "Packages processing into a custom node with named ports. Instances share a definition but have independent DSP state.", "Выдели Gain и LFO, сохрани внешние соединения и создай Custom Node. Открой её двойным щелчком для редактирования.", "Select Gain and LFO, retain the external connections and create a Custom Node. Double-click it to edit its contents.", ["subgraph_input", "subgraph_output", "map", "cpp_function"], "До 16 портов на сторону, вложенность до 8. Oversampling 1×/2×/4× задаёт границу частоты; перед разворачиванием выбери 1×.", "Up to 16 ports per side and 8 nesting levels. Oversampling 1×/2×/4× defines a rate boundary; choose 1× before expanding.");
add("subgraph_input", "Представляет вход собственной ноды внутри её графа. Тип, диапазон и значение по умолчанию задаются интерфейсом подграфа.", "Represents a custom node’s input inside its graph. Type, range and default come from the subgraph interface.", "Number-порт Cutoff → Node Input → Biquad Coefficients / Frequency.", "Number port Cutoff → Node Input → Biquad Coefficients / Frequency.", ["subgraph", "subgraph_output", "biquad_coefficients"], "Используется внутри Custom Node, не вместо верхнеуровневого Input.", "Use this inside a Custom Node, not in place of the top-level Input.");
add("subgraph_output", "Передаёт внутренний результат в именованный выход собственной ноды.", "Passes an internal result to a custom node’s named output.", "Biquad / Output → Node Output с типом Audio; снаружи выход собственной ноды подключается к Output.", "Biquad / Output → an Audio Node Output; outside, connect the custom node’s output to Output.", ["subgraph", "subgraph_input", "output"]);
add("cpp_function", "Создаёт переносимую C++23-функцию. Сигнатура определяет Audio, Number, Gate и Function-порты; SDK управляет состоянием и подготовкой.", "Creates a portable C++23 function. Its signature defines Audio, Number, Gate and Function ports; the SDK manages state and preparation.", "Добавь C++ Function, напиши process(AudioFrame audio, float gain = 0.5), обнови ноду и соедини Input → Audio, результат → Output.", "Add a C++ Function, write process(AudioFrame audio, float gain = 0.5), update the node, then connect Input → Audio and its result → Output.", ["input", "output", "interface", "subgraph"], "После каждой правки кода обновляй порты. Function-связь требует совпадения полной сигнатуры; рекурсивные вызовы запрещены. Compile выпускает .vltmini.", "Update ports after every code edit. Function bindings require an exact signature match; recursive calls are forbidden. Compile produces a .vltmini.");

export const nodeCopy = copy;
