#!/usr/bin/env python3
"""Turn prompts/ into the built-in prompt pack, for C++ and for Go.

The assistant's instructions live in `prompts/` as Markdown with a small front
matter block. Two programs need that text: the desktop app, which compiles it in
as the offline fallback, and the backend, which seeds the database with it and
restores it when an editor in the admin panel asks for the original back.

Rather than keeping three copies in step by hand, both are generated from the
one source:

    python3 scripts/gen_prompts.py           # write the generated files
    python3 scripts/gen_prompts.py --check   # fail if they are out of date

Front matter is deliberately not YAML — four known keys, parsed here, so the
build needs no third-party module.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROMPTS = ROOT / "prompts"
CPP_OUT = ROOT / "controller" / "ai" / "PromptsBuiltin.cpp"
GO_OUT = ROOT / "backend" / "internal" / "promptlib" / "builtin_gen.go"

BANNER = "Generated by scripts/gen_prompts.py from prompts/. Do not edit by hand."


class Document:
    def __init__(self, path: Path, kind: str):
        text = path.read_text(encoding="utf-8")
        if not text.startswith("---\n"):
            raise SystemExit(f"{path}: missing front matter")
        end = text.find("\n---\n", 3)
        if end < 0:
            raise SystemExit(f"{path}: front matter is not closed")
        head, body = text[4:end], text[end + 5 :]

        fields: dict[str, str] = {}
        for line in head.splitlines():
            if not line.strip():
                continue
            key, _, value = line.partition(":")
            if not _:
                raise SystemExit(f"{path}: cannot read front-matter line {line!r}")
            fields[key.strip()] = value.strip()

        self.kind = kind
        self.id = fields.get("id", path.stem)
        self.title = fields.get("title", self.id)
        self.use_when = fields.get("use_when", "")
        self.body = body.strip() + "\n"
        raw_tags = fields.get("tags", "").strip()
        if raw_tags.startswith("[") and raw_tags.endswith("]"):
            raw_tags = raw_tags[1:-1]
        self.tags = [tag.strip() for tag in raw_tags.split(",") if tag.strip()]

        if not self.id or not all(c.isalnum() or c == "-" for c in self.id):
            raise SystemExit(f"{path}: id {self.id!r} must be [a-z0-9-]")
        if not self.body.strip():
            raise SystemExit(f"{path}: body is empty")
        if ')PROMPT"' in text:
            raise SystemExit(f"{path}: contains the C++ raw-string terminator")


def load() -> tuple[Document, list[Document]]:
    main = Document(PROMPTS / "main.md", "main")
    playbooks = [
        Document(path, "playbook")
        for path in sorted((PROMPTS / "playbooks").glob("*.md"))
    ]
    if not playbooks:
        raise SystemExit("no playbooks found in prompts/playbooks")
    seen: set[str] = set()
    for book in playbooks:
        if book.id in seen:
            raise SystemExit(f"duplicate playbook id {book.id!r}")
        seen.add(book.id)
    return main, playbooks


def version_of(main: Document, playbooks: list[Document]) -> str:
    digest = hashlib.sha256()
    for doc in [main, *playbooks]:
        for part in (doc.id, doc.title, doc.use_when, ",".join(doc.tags), doc.body):
            digest.update(part.encode("utf-8"))
            digest.update(b"\x00")
    return "builtin-" + digest.hexdigest()[:12]


def cpp_raw(text: str) -> str:
    return 'R"PROMPT(' + text + ')PROMPT"'


def render_cpp(main: Document, playbooks: list[Document], version: str) -> str:
    out = [
        f"// {BANNER}",
        "//",
        "// The instructions the assistant works under, compiled in. A pack",
        "// downloaded from the server replaces this at runtime; this is what is",
        "// used on a first run, offline, and whenever the download is refused.",
        "",
        '#include "ai/Prompts.hpp"',
        "",
        "namespace daw::ai {",
        "",
        "const PromptPack& builtinPrompts() {",
        "    static const PromptPack pack = [] {",
        "        PromptPack p;",
        f'        p.version = "{version}";',
        "        p.main = " + cpp_raw(main.body) + ";",
        f"        p.playbooks.reserve({len(playbooks)});",
    ]
    for book in playbooks:
        tags = ", ".join(json.dumps(tag) for tag in book.tags)
        out += [
            "        p.playbooks.push_back(Playbook{",
            f"            {json.dumps(book.id)},",
            f"            {json.dumps(book.title)},",
            f"            {json.dumps(book.use_when)},",
            "            " + cpp_raw(book.body) + ",",
            f"            {{{tags}}}}});",
        ]
    out += [
        "        return p;",
        "    }();",
        "    return pack;",
        "}",
        "",
        "} // namespace daw::ai",
        "",
    ]
    return "\n".join(out)


def render_go(main: Document, playbooks: list[Document], version: str) -> str:
    def literal(text: str) -> str:
        return json.dumps(text)

    out = [
        f"// Code generated by scripts/gen_prompts.py. DO NOT EDIT.",
        "",
        "package promptlib",
        "",
        "// Version identifies this build's built-in text. The served pack keeps its",
        "// own version, derived from the rows in the database.",
        f"const Version = {literal(version)}",
        "",
        "// Builtin returns the documents a fresh database is seeded with, and the",
        "// text an admin gets back when they revert an edited document.",
        "func Builtin() []Document {",
        "\treturn []Document{",
        "\t\t{",
        f"\t\t\tID:      {literal(main.id)},",
        f'\t\t\tKind:    "main",',
        f"\t\t\tTitle:   {literal(main.title)},",
        f"\t\t\tUseWhen: {literal(main.use_when)},",
        f"\t\t\tTags:    []string{{}},",
        f"\t\t\tBody:    {literal(main.body)},",
        "\t\t},",
    ]
    for book in playbooks:
        tags = ", ".join(literal(tag) for tag in book.tags)
        out += [
            "\t\t{",
            f"\t\t\tID:      {literal(book.id)},",
            f'\t\t\tKind:    "playbook",',
            f"\t\t\tTitle:   {literal(book.title)},",
            f"\t\t\tUseWhen: {literal(book.use_when)},",
            f"\t\t\tTags:    []string{{{tags}}},",
            f"\t\t\tBody:    {literal(book.body)},",
            "\t\t},",
        ]
    out += ["\t}", "}", ""]
    return "\n".join(out)


def main_entry() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the generated files are stale")
    args = parser.parse_args()

    main, playbooks = load()
    version = version_of(main, playbooks)
    wanted = {CPP_OUT: render_cpp(main, playbooks, version),
              GO_OUT: render_go(main, playbooks, version)}

    stale = []
    for path, text in wanted.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        stale.append(path)
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")

    if args.check and stale:
        for path in stale:
            print(f"stale: {path.relative_to(ROOT)}", file=sys.stderr)
        print("run: python3 scripts/gen_prompts.py", file=sys.stderr)
        return 1

    print(f"{version}: 1 main + {len(playbooks)} playbooks"
          + (f", wrote {len(stale)} file(s)" if stale else ", up to date"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main_entry())
