/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMeta"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLatestRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getRelease"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/{version}/download/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["downloadReleaseArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/releases/{version}/screenshots/{screenshotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReleaseScreenshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/web/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/web/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["webLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/web/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["webLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/web/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/web/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/quota": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyQuota"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMyDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/devices/{deviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeMyDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/bug-reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createBugReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["desktopLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["desktopRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["desktopLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["desktopMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/telemetry/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadTelemetryBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/crashes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["uploadCrash"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public metadata for enabled administrator-managed models */
        get: operations["listDesktopAIModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/ai/models/{modelId}/lease": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check the current model and quota, then issue its direct provider configuration for one request */
        post: operations["leaseDesktopAIModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/ai/reservations/{reservationId}/settle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Settle a direct provider request against the authenticated user's reservation */
        post: operations["settleDesktopAIReservation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/ai/models/{modelId}/invoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compatibility proxy for older desktop builds
         * @deprecated
         */
        post: operations["invokeDesktopAIModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/desktop/ai/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The assistant's instructions — the main prompt and every playbook
         * @description Served rather than compiled in, so the assistant's behaviour can be edited in the admin panel without a release. Send If-None-Match with the ETag of the copy already cached; the usual answer is 304.
         *
         */
        get: operations["getAIPrompts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ai/prompts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListAIPrompts"];
        put?: never;
        /** Add a playbook */
        post: operations["adminCreateAIPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ai/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListAIModels"];
        put?: never;
        post: operations["adminCreateAIModel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ai/models/{modelId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["adminUpdateAIModel"];
        post?: never;
        delete: operations["adminDeleteAIModel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ai/prompts/{promptId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promptId: string;
            };
            cookie?: never;
        };
        get: operations["adminGetAIPrompt"];
        /** Edit a document, keeping the text it replaced as a revision */
        put: operations["adminUpdateAIPrompt"];
        post?: never;
        delete: operations["adminDeleteAIPrompt"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ai/prompts/{promptId}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Put back the text the desktop build ships with */
        post: operations["adminRevertAIPrompt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/ai/prompts/{promptId}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminAIPromptRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetUser"];
        put?: never;
        post?: never;
        delete: operations["adminDeleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetUserTelemetry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/ledger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetUserTokenLedger"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/suspend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminSuspendUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminActivateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/tokens/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminAddUserTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/tokens/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminResetUserTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/devices/{deviceId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminRevokeUserDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/sessions/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminRevokeUserSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/users/{userId}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["adminDeleteUserDiagnostics"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/bugs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListBugs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/bugs/{bugId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["adminUpdateBug"];
        trace?: never;
    };
    "/v1/admin/bugs/{bugId}/attachments/{attachmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminDownloadBugAttachment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/crashes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListCrashes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/crashes/{crashId}/artifact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminDownloadCrashArtifact"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/releases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminListReleases"];
        put?: never;
        post: operations["adminCreateRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/releases/{releaseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetRelease"];
        put: operations["adminUpdateRelease"];
        post?: never;
        delete: operations["adminDeleteRelease"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/releases/{releaseId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminPublishRelease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/releases/{releaseId}/artifacts/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminUploadReleaseArtifact"];
        post?: never;
        delete: operations["adminDeleteReleaseArtifact"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/releases/{releaseId}/screenshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["adminUploadReleaseScreenshot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/releases/{releaseId}/screenshots/{screenshotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["adminUpdateReleaseScreenshot"];
        post?: never;
        delete: operations["adminDeleteReleaseScreenshot"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/releases/{releaseId}/screenshots/{screenshotId}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["adminGetReleaseScreenshotFile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        APIError: {
            code: string;
            message: string;
            field_errors?: {
                [key: string]: string;
            };
            request_id: string;
        };
        /** @enum {string} */
        ArtifactKind: "windows-exe" | "macos-dmg" | "linux-appimage" | "linux-deb" | "linux-rpm" | "linux-tar-gz" | "linux-tar-xz";
        ReleaseArtifact: {
            /** Format: uuid */
            id: string;
            kind: components["schemas"]["ArtifactKind"];
            /** @enum {string} */
            platform: "windows" | "macos" | "linux";
            label: string;
            file_name: string;
            /** Format: int64 */
            bytes: number;
            sha256: string;
            download_url: string;
            /** Format: date-time */
            updated_at: string;
        };
        ReleaseScreenshot: {
            /** Format: uuid */
            id: string;
            caption?: string;
            caption_ru?: string;
            caption_en?: string;
            sort_order: number;
            width: number;
            height: number;
            sha256: string;
            url: string;
        };
        PublicRelease: {
            /** Format: uuid */
            id: string;
            version: string;
            summary: string;
            features: string[];
            changes: string[];
            fixes: string[];
            artifacts: components["schemas"]["ReleaseArtifact"][];
            screenshots: components["schemas"]["ReleaseScreenshot"][];
            /** Format: uri */
            page_url: string;
            /** Format: date-time */
            published_at: string;
        };
        AdminRelease: {
            /** Format: uuid */
            id: string;
            version: string;
            /** @enum {string} */
            status: "draft" | "published";
            summary_ru: string;
            summary_en: string;
            features_ru: string[];
            features_en: string[];
            changes_ru: string[];
            changes_en: string[];
            fixes_ru: string[];
            fixes_en: string[];
            artifacts: components["schemas"]["ReleaseArtifact"][];
            screenshots: components["schemas"]["ReleaseScreenshot"][];
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ReleaseWrite: {
            version: string;
            summary_ru: string;
            summary_en: string;
            features_ru: string[];
            features_en: string[];
            changes_ru: string[];
            changes_en: string[];
            fixes_ru: string[];
            fixes_en: string[];
        };
        ReleaseScreenshotWrite: {
            caption_ru: string;
            caption_en: string;
            sort_order: number;
        };
        LatestRelease: {
            version: string;
            /** Format: date-time */
            published_at: string;
            /** Format: uri */
            page_url: string;
        };
        DesktopAIModel: {
            /** Format: uuid */
            id: string;
            display_name: string;
            /** @enum {string} */
            provider: "openai" | "anthropic";
            model: string;
        };
        AIModelLease: {
            /** Format: uuid */
            reservation_id: string;
            /** Format: int64 */
            reserved_tokens: number;
            /** @enum {string} */
            provider: "openai" | "anthropic";
            model: string;
            /** Format: uri */
            endpoint_url: string;
            /** @description Ephemeral provider credential; never persist it */
            api_key: string;
        };
        AdminAIModel: components["schemas"]["DesktopAIModel"] & {
            /** Format: uri */
            endpoint_url: string;
            has_api_key: boolean;
            enabled: boolean;
            sort_order: number;
        };
        AIModelWrite: {
            display_name: string;
            /** @enum {string} */
            provider: "openai" | "anthropic";
            model: string;
            /** Format: uri */
            endpoint_url: string;
            api_key: string;
            enabled: boolean;
            sort_order: number;
        };
        Meta: {
            /** @constant */
            service?: "vlt-studio";
            /** @constant */
            api_version?: "v1";
            consent_version?: string;
            /** @constant */
            offline_hours?: 72;
            /** @constant */
            access_token_minutes?: 15;
            public_key?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            nickname: string;
            password: string;
            password_confirmation: string;
            /** @enum {string} */
            locale: "ru" | "en";
            /** @constant */
            consent_accepted: true;
            consent_version: string;
        };
        PasswordResetConfirmRequest: {
            token: string;
            password: string;
            password_confirmation: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            nickname: string;
            /** @enum {string} */
            locale: "ru" | "en";
            /** @enum {string} */
            status: "active" | "suspended";
            consent_version?: string;
            /** Format: date-time */
            consent_accepted_at?: string;
            /** Format: date-time */
            created_at?: string;
        };
        Quota: {
            /** Format: int64 */
            base_limit: number;
            /** Format: int64 */
            adjustment: number;
            /** Format: int64 */
            used_tokens: number;
            /** Format: int64 */
            reserved_tokens: number;
            /** Format: int64 */
            remaining_tokens: number;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            ends_at: string;
        };
        Device: {
            /** Format: uuid */
            id: string;
            display_name: string;
            /** @enum {string} */
            platform: "windows" | "macos";
            os_version: string;
            app_version: string;
            hardware?: components["schemas"]["HardwareSnapshot"];
            /** Format: date-time */
            first_seen_at: string;
            /** Format: date-time */
            last_seen_at: string;
            /** Format: date-time */
            revoked_at?: string | null;
        };
        HardwareSnapshot: {
            cpu_model?: string;
            cpu_cores?: number;
            cpu_threads?: number;
            gpu?: {
                name?: string;
                driver?: string;
            }[];
            /** Format: int64 */
            ram_bytes?: number;
            os_name?: string;
            os_version?: string;
            arch?: string;
        };
        AccountSession: {
            user: components["schemas"]["User"];
            csrf_token?: string;
            subscription: {
                /** @constant */
                plan?: "demo";
                /** @constant */
                display_name?: "Demo";
                /** @constant */
                all_features?: true;
            };
            quota: components["schemas"]["Quota"];
        };
        DesktopLoginRequest: {
            /** Format: email */
            email: string;
            password: string;
            /**
             * Format: uuid
             * @description Random installation UUID; never hardware-derived
             */
            installation_id: string;
            device_name: string;
            /** @enum {string} */
            platform: "windows" | "macos";
            os_version: string;
            app_version: string;
            hardware: components["schemas"]["HardwareSnapshot"];
        };
        DesktopRefreshRequest: {
            refresh_token: string;
            app_version: string;
        };
        DesktopSession: components["schemas"]["AccountSession"] & {
            access_token: string;
            refresh_token: string;
            reporter_token: string;
            /** Format: date-time */
            reporter_expires_at: string;
            offline_entitlement: string;
            /** Format: date-time */
            server_time: string;
            public_key: string;
        };
        TelemetryBatch: {
            events: components["schemas"]["TelemetryEvent"][];
        };
        TelemetryEvent: {
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            session_id: string;
            /** @enum {string} */
            kind: "session_started" | "sample" | "session_ended";
            /** Format: date-time */
            occurred_at: string;
            /** @description Strict kind-specific allowlist; never project content or paths */
            payload: Record<string, never>;
        };
        CrashMetadata: {
            /** Format: uuid */
            session_id?: string | null;
            /** Format: uuid */
            report_id: string;
            build_id: string;
            app_version: string;
            /** @enum {string} */
            platform: "windows" | "macos";
            reason: string;
            last_plugin?: string;
            /** Format: date-time */
            occurred_at: string;
            exception_code?: string;
            signal?: string;
            health_samples?: Record<string, never>[];
            modules?: Record<string, never>[];
        };
        BugReportRequest: {
            title: string;
            description: string;
            steps?: string;
            expected?: string;
            actual?: string;
            attachments?: string[];
        };
        BugUpdateRequest: {
            /** @enum {string} */
            status: "new" | "triage" | "in_progress" | "fixed" | "duplicate" | "wont_fix";
            internal_note: string;
        };
    };
    responses: {
        /** @description Structured API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["APIError"];
            };
        };
        /** @description Authenticated account state */
        AccountSession: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AccountSession"];
            };
        };
        /** @description Rotating desktop credentials and offline entitlement */
        DesktopSession: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["DesktopSession"];
            };
        };
    };
    parameters: {
        UserId: string;
        DeviceId: string;
        BugId: string;
        AttachmentId: string;
        CrashId: string;
        ReleaseId: string;
        ReleaseVersion: string;
        ScreenshotId: string;
        ArtifactKind: components["schemas"]["ArtifactKind"];
        Platform: "windows" | "macos" | "linux";
        Locale: "ru" | "en";
    };
    requestBodies: {
        Login: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        PasswordConfirmation: {
            content: {
                "application/json": {
                    password: string;
                };
            };
        };
        AIProviderRequest: {
            content: {
                "application/json": {
                    model: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        AILeaseRequest: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    input_bytes: number;
                    /** Format: int64 */
                    max_output_tokens: number;
                };
            };
        };
        AISettlementRequest: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    actual_tokens: number;
                    /** @enum {string} */
                    outcome: "provider_usage" | "provider_rejected" | "transport_failure" | "cancelled" | "conservative_no_usage";
                };
            };
        };
        AIModelWrite: {
            content: {
                "application/json": components["schemas"]["AIModelWrite"];
            };
        };
        ReleaseWrite: {
            content: {
                "application/json": components["schemas"]["ReleaseWrite"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMeta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    listReleases: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published releases ordered by semantic version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        releases: components["schemas"]["PublicRelease"][];
                    };
                };
            };
        };
    };
    getLatestRelease: {
        parameters: {
            query: {
                platform: components["parameters"]["Platform"];
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest release with an installer for the requested platform */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LatestRelease"];
                };
            };
            /** @description No published release supports this platform */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getRelease: {
        parameters: {
            query?: {
                locale?: components["parameters"]["Locale"];
            };
            header?: never;
            path: {
                version: components["parameters"]["ReleaseVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Localized published release */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicRelease"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    downloadReleaseArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: components["parameters"]["ReleaseVersion"];
                kind: components["parameters"]["ArtifactKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installer with Range */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    getReleaseScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: components["parameters"]["ReleaseVersion"];
                screenshotId: components["parameters"]["ScreenshotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitized release screenshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            201: components["responses"]["AccountSession"];
            422: components["responses"]["Error"];
        };
    };
    webLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Login"];
        responses: {
            200: components["responses"]["AccountSession"];
            401: components["responses"]["Error"];
        };
    };
    webLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Error"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description Accepted regardless of account existence */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Password changed and sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AccountSession"];
        };
    };
    getMyQuota: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current UTC cycle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quota"];
                };
            };
        };
    };
    listMyDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Devices, including revoked history and the active-device limit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        devices: components["schemas"]["Device"][];
                        /** @constant */
                        limit: 2;
                    };
                };
            };
        };
    };
    revokeMyDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    createBugReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["BugReportRequest"];
            };
        };
        responses: {
            /** @description One-way report receipt */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
        };
    };
    desktopLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesktopLoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["DesktopSession"];
            409: components["responses"]["Error"];
        };
    };
    desktopRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DesktopRefreshRequest"];
            };
        };
        responses: {
            200: components["responses"]["DesktopSession"];
            401: components["responses"]["Error"];
        };
    };
    desktopLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    desktopMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AccountSession"];
        };
    };
    uploadTelemetryBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelemetryBatch"];
            };
        };
        responses: {
            /** @description Idempotent batch accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
        };
    };
    uploadCrash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description JSON-encoded CrashMetadata object */
                    metadata: string;
                    /**
                     * Format: binary
                     * @description UTF-8 crash log preferred; at most 50 MiB
                     */
                    artifact?: string;
                };
            };
        };
        responses: {
            /** @description Crash stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDesktopAIModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Selectable managed models; endpoint URLs and provider keys are issued only by a checked one-request lease */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        models?: components["schemas"]["DesktopAIModel"][];
                    };
                };
            };
        };
    };
    leaseDesktopAIModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AILeaseRequest"];
        responses: {
            /** @description Ephemeral direct-provider configuration; must not be cached or persisted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIModelLease"];
                };
            };
            402: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    settleDesktopAIReservation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reservationId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AISettlementRequest"];
        responses: {
            /** @description Updated quota after settlement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        quota: components["schemas"]["Quota"];
                    };
                };
            };
            404: components["responses"]["Error"];
        };
    };
    invokeDesktopAIModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AIProviderRequest"];
        responses: {
            /** @description Provider JSON or SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            402: components["responses"]["Error"];
        };
    };
    getAIPrompts: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The prompt pack */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unchanged since the cached copy */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            503: components["responses"]["Error"];
        };
    };
    adminListAIPrompts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every instruction document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminCreateAIPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new document */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    adminListAIModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every administrator-managed model; keys are represented only by has_api_key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        models?: components["schemas"]["AdminAIModel"][];
                    };
                };
            };
        };
    };
    adminCreateAIModel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AIModelWrite"];
        responses: {
            /** @description Model created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
        };
    };
    adminUpdateAIModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["AIModelWrite"];
        responses: {
            /** @description Model updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    adminDeleteAIModel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                modelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    adminGetAIPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    adminUpdateAIPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The saved document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
        };
    };
    adminDeleteAIPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
        };
    };
    adminRevertAIPrompt: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The restored document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            422: components["responses"]["Error"];
        };
    };
    adminAIPromptRevisions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                promptId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The last 50 revisions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["Login"];
        responses: {
            /** @description Admin session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    adminLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current administrator and CSRF token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error"];
        };
    };
    adminDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operational counters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminListUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminDeleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PasswordConfirmation"];
        responses: {
            /** @description Account and related data deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetUserTelemetry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sessions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetUserTokenLedger: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current quota cycle and immutable token ledger */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminSuspendUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User suspended and all sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminActivateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User activated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminAddUserTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    amount: number;
                };
            };
        };
        responses: {
            /** @description Updated current UTC quota cycle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quota"];
                };
            };
        };
    };
    adminResetUserTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PasswordConfirmation"];
        responses: {
            /** @description Reset current UTC quota cycle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quota"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    adminRevokeUserDevice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
                deviceId: components["parameters"]["DeviceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device and its desktop sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminRevokeUserSessions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Web and desktop sessions revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminDeleteUserDiagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Telemetry */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminListBugs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bug registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminUpdateBug: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BugUpdateRequest"];
            };
        };
        responses: {
            /** @description Bug status and internal note updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminDownloadBugAttachment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                bugId: components["parameters"]["BugId"];
                attachmentId: components["parameters"]["AttachmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitized image attachment */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                    "image/png": unknown;
                    "image/webp": unknown;
                };
            };
        };
    };
    adminListCrashes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Crash registry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminDownloadCrashArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crashId: components["parameters"]["CrashId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Readable crash log or a legacy binary artifact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                    "application/json": unknown;
                    "application/octet-stream": unknown;
                };
            };
            404: components["responses"]["Error"];
        };
    };
    adminAudit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Append-only administrative audit */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminListReleases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft and published releases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        releases: components["schemas"]["AdminRelease"][];
                    };
                };
            };
        };
    };
    adminCreateRelease: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ReleaseWrite"];
        responses: {
            /** @description Saved draft */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRelease"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    adminGetRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Release editor state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRelease"];
                };
            };
        };
    };
    adminUpdateRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["ReleaseWrite"];
        responses: {
            /** @description Saved release */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRelease"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    adminDeleteRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Draft and stored files deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    adminPublishRelease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Published release */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminRelease"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    adminUploadReleaseArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
                kind: components["parameters"]["ArtifactKind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Uploaded or atomically replaced artifact */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseArtifact"];
                };
            };
            413: components["responses"]["Error"];
            422: components["responses"]["Error"];
        };
    };
    adminDeleteReleaseArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
                kind: components["parameters"]["ArtifactKind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artifact deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    adminUploadReleaseScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    caption_ru?: string;
                    caption_en?: string;
                    sort_order?: number;
                };
            };
        };
        responses: {
            /** @description Sanitized screenshot */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseScreenshot"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    adminUpdateReleaseScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
                screenshotId: components["parameters"]["ScreenshotId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReleaseScreenshotWrite"];
            };
        };
        responses: {
            /** @description Updated screenshot metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseScreenshot"];
                };
            };
        };
    };
    adminDeleteReleaseScreenshot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
                screenshotId: components["parameters"]["ScreenshotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Screenshot deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminGetReleaseScreenshotFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                releaseId: components["parameters"]["ReleaseId"];
                screenshotId: components["parameters"]["ScreenshotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sanitized screenshot preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                };
            };
            404: components["responses"]["Error"];
        };
    };
}
