# CPU inference only; model export and corpus tooling are developer-only Python.
option(DAW_ENABLE_NEURAL_ANALYSIS "Enable bundled Beat This! and S-KEY models" ON)
set(DAW_ONNXRUNTIME_ROOT "" CACHE PATH "Optional preinstalled ONNX Runtime SDK")
if(DAW_ENABLE_NEURAL_ANALYSIS)
    # Official 1.22 archives have a broken include path in their CMake export.
    # Import the documented C API layout directly instead.
    if(NOT DAW_ONNXRUNTIME_ROOT)
        if(APPLE)
            if(CMAKE_SYSTEM_PROCESSOR MATCHES "arm64|aarch64" AND NOT CMAKE_OSX_ARCHITECTURES MATCHES "x86_64")
                set(ort_platform "osx-arm64")
                set(ort_hash "cab6dcbd77e7ec775390e7b73a8939d45fec3379b017c7cb74f5b204c1a1cc07")
            else()
                set(ort_platform "osx-universal2")
                set(ort_hash "cfa6f6584d87555ed9f6e7e8a000d3947554d589efe3723b8bfa358cd263d03c")
            endif()
        elseif(WIN32 AND CMAKE_SIZEOF_VOID_P EQUAL 8 AND NOT CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
            set(ort_platform "win-x64")
            set(ort_hash "174c616efc0271194488642a72f1a514e01487da4dfe84c49296d66e40ebe0da")
        elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "x86_64|AMD64")
            set(ort_platform "linux-x64")
            set(ort_hash "8344d55f93d5bc5021ce342db50f62079daf39aaafb5d311a451846228be49b3")
        else()
            message(FATAL_ERROR "Set DAW_ONNXRUNTIME_ROOT for this architecture, or DAW_ENABLE_NEURAL_ANALYSIS=OFF")
        endif()
        set(ort_name "onnxruntime-${ort_platform}-1.22.0")
        if(EXISTS "${CMAKE_SOURCE_DIR}/.cache/audio-analysis/${ort_name}/include/onnxruntime_cxx_api.h")
            set(DAW_ONNXRUNTIME_ROOT "${CMAKE_SOURCE_DIR}/.cache/audio-analysis/${ort_name}")
        else()
            include(FetchContent)
            if(WIN32)
                set(ort_ext zip)
            else()
                set(ort_ext tgz)
            endif()
            FetchContent_Declare(vlt_ort URL "https://github.com/microsoft/onnxruntime/releases/download/v1.22.0/${ort_name}.${ort_ext}"
                URL_HASH "SHA256=${ort_hash}" DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
            FetchContent_MakeAvailable(vlt_ort)
            set(DAW_ONNXRUNTIME_ROOT "${vlt_ort_SOURCE_DIR}")
        endif()
    endif()
    unset(ort_include CACHE)
    unset(ort_library CACHE)
    find_path(ort_include onnxruntime_cxx_api.h HINTS "${DAW_ONNXRUNTIME_ROOT}/include" "${DAW_ONNXRUNTIME_ROOT}/include/onnxruntime" REQUIRED NO_DEFAULT_PATH)
    find_library(ort_library NAMES onnxruntime HINTS "${DAW_ONNXRUNTIME_ROOT}/lib" REQUIRED NO_DEFAULT_PATH)
    add_library(onnxruntime::onnxruntime SHARED IMPORTED GLOBAL)
    set_target_properties(onnxruntime::onnxruntime PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${ort_include}" IMPORTED_LOCATION "${ort_library}")
    if(WIN32)
        set_target_properties(onnxruntime::onnxruntime PROPERTIES IMPORTED_IMPLIB "${ort_library}"
            IMPORTED_LOCATION "${DAW_ONNXRUNTIME_ROOT}/lib/onnxruntime.dll")
    endif()
    if(WIN32)
        set(ort_runtime_directory "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}")
        if(CMAKE_CONFIGURATION_TYPES)
            string(APPEND ort_runtime_directory "/$<CONFIG>")
        endif()
        file(GLOB ort_dlls "${DAW_ONNXRUNTIME_ROOT}/lib/*.dll")
        add_custom_command(TARGET daw_controller POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E make_directory "${ort_runtime_directory}"
            COMMAND ${CMAKE_COMMAND} -E copy_if_different ${ort_dlls} "${ort_runtime_directory}")
    endif()
    target_link_libraries(daw_controller PRIVATE onnxruntime::onnxruntime)
    target_compile_definitions(daw_controller PRIVATE DAW_HAS_ONNX_ANALYSIS=1)
else()
    target_compile_definitions(daw_controller PRIVATE DAW_HAS_ONNX_ANALYSIS=0)
endif()
if(NOT DAW_PACKAGE)
    target_compile_definitions(daw_controller PRIVATE
        DAW_ANALYSIS_DEV_MODELS="${CMAKE_SOURCE_DIR}/models/audio-analysis")
endif()

function(daw_install_audio_analysis target)
    set(assets "${CMAKE_SOURCE_DIR}/models/audio-analysis")
    if(NOT EXISTS "${assets}/manifest.json")
        message(FATAL_ERROR "Missing musical analysis models/manifest.json; run tools/audio-analysis/export_models.py")
    endif()
    if(DAW_ENABLE_NEURAL_ANALYSIS)
        file(GLOB_RECURSE analysis_assets CONFIGURE_DEPENDS "${assets}/*")
    else()
        # DSP-only packages still need their independently fitted calibration.
        set(analysis_assets "${assets}/manifest.json" "${assets}/calibration.json")
    endif()
    set_property(TARGET ${target} APPEND PROPERTY LINK_DEPENDS ${analysis_assets})
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${assets}/manifest.json")
    if(APPLE AND DAW_PACKAGE)
        set(analysis_destination "${DAW_BUNDLE_NAME}.app/Contents/Resources/audio-analysis")
        set(analysis_build_destination "$<TARGET_BUNDLE_CONTENT_DIR:${target}>/Resources/audio-analysis")
    else()
        set(analysis_destination bin/audio-analysis)
        set(analysis_build_destination "$<TARGET_FILE_DIR:${target}>/audio-analysis")
    endif()
    if(DAW_ENABLE_NEURAL_ANALYSIS)
        file(READ "${assets}/manifest.json" manifest)
        foreach(name beat-this-final0.onnx skey.onnx mel-filterbank.bin)
            string(JSON expected GET "${manifest}" sha256 "${name}")
            file(SHA256 "${assets}/${name}" actual)
            if(NOT actual STREQUAL expected)
                message(FATAL_ERROR "Musical analysis asset checksum mismatch: ${name}")
            endif()
        endforeach()
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_directory "${assets}"
                    "${analysis_build_destination}")
        install(DIRECTORY "${assets}/" DESTINATION "${analysis_destination}")
    else()
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E make_directory "${analysis_build_destination}"
            COMMAND ${CMAKE_COMMAND} -E copy_if_different ${analysis_assets}
                    "${analysis_build_destination}")
        install(FILES ${analysis_assets} DESTINATION "${analysis_destination}")
        return()
    endif()
    get_target_property(analysis_runtime_file onnxruntime::onnxruntime IMPORTED_LOCATION)
    get_filename_component(analysis_runtime_directory "${analysis_runtime_file}" DIRECTORY)
    if(WIN32)
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E copy_if_different
                "$<TARGET_FILE:onnxruntime::onnxruntime>" "$<TARGET_FILE_DIR:${target}>")
        file(GLOB analysis_runtime_dlls "${analysis_runtime_directory}/*.dll")
        install(FILES ${analysis_runtime_dlls} DESTINATION bin)
    elseif(APPLE AND DAW_PACKAGE)
        # Keep the linked runtime resolvable after installation removes build
        # rpaths, before macdeployqt inspects the installed executable.
        get_filename_component(analysis_runtime_real "${analysis_runtime_file}" REALPATH)
        get_filename_component(analysis_runtime_name "${analysis_runtime_real}" NAME)
        set_property(TARGET ${target} APPEND PROPERTY INSTALL_RPATH "@executable_path/../Frameworks")
        add_custom_command(TARGET ${target} POST_BUILD
            COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_BUNDLE_CONTENT_DIR:${target}>/Frameworks"
            COMMAND ${CMAKE_COMMAND} -E copy_if_different "${analysis_runtime_real}"
                "$<TARGET_BUNDLE_CONTENT_DIR:${target}>/Frameworks/${analysis_runtime_name}")
    elseif(NOT APPLE)
        set_property(TARGET ${target} APPEND PROPERTY INSTALL_RPATH "$ORIGIN")
        file(GLOB analysis_runtime_libraries "${analysis_runtime_directory}/libonnxruntime.so*")
        install(FILES ${analysis_runtime_libraries} DESTINATION bin)
    endif()
    # macdeployqt handles the remaining Qt dependencies and bundle signing.
endfunction()
